### ISSUE TITLE
extension breaks when package.json is invalid

### ISSUE THREAD

**Issue by hakobpogh** [tailwindlabs/tailwindcss-intellisense#666] opened 2022-11-17 10:51 UTC
**What version of Tailwind CSS IntelliSense are you using?**
v0.9.1

**What version of Tailwind CSS are you using?**
v3.1.8

**What package manager are you using?**
yarn

**What operating system are you using?**
macOS

**Tailwind config**

```js
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');
const { join } = require('path');

module.exports = {
  corePlugins: { preflight: false },

  content: [
    ...createGlobPatternsForDependencies(__dirname),
    join(__dirname, 'components/**/**/*!(*.stories|*.spec).{ts,tsx,html}'),
    join(__dirname, 'components/**/*!(*.stories|*.spec).{ts,tsx,html}'),
    join(__dirname, 'components/*!(*.stories|*.spec).{ts,tsx,html}'),
    join(__dirname, '**/*!(*.stories|*.spec).{ts,tsx,html}'),
    join(__dirname, 'pages/**/**/*.{js,jsx,ts,tsx}'),
    join(__dirname, 'pages/**/*.{js,jsx,ts,tsx}'),
    join(__dirname, 'pages/*.{js,jsx,ts,tsx}'),
    join(__dirname, 'components/**/**/*.{js,jsx,ts,tsx}'),
    join(__dirname, 'components/**/*.{js,jsx,ts,tsx}'),
    join(__dirname, 'components/*.{js,jsx,ts,tsx}'),
  ],
  plugins: [],
  presets: [require('../../tailwind.preset')],
  theme: {
    extend: {},
  },
};
```

**VS Code settings**

```json
none of the tailwind props were changed in my settings.json
```

**Reproduction URL**
N/A

**Describe your issue**

When during rebase I have a conflict in package.json file the extension fails and after that when I edit files, extension freezes and doesn't allow saving any file. And I have no option for restarting it or fixing the problem.

**Comment by bradlc** [comment] 2022-12-13 15:09
Hey. Please can you share a GitHub repository that I can clone and open in VS Code to reproduce the issue? Unfortunately without that it's not going to be possible to debug the issue. Thanks!

**Comment by hakobpogh** [comment] 2022-12-26 19:02
No, actually, it's just happening sometimes. Can I copy some file which will provide some info about it?

**Comment by bradlc** [comment] 2023-01-10 12:24
It's fine if it only happens sometimes. We still require a GitHub repository where you already have everything all set up so we can clone it and reproduce the issue (even just sometimes) without configuring everything by hand.

**Comment by hakobpogh** [comment] 2023-01-20 10:01
Something similar also happens to eslint and typescript, but they have some `restart ESLINT` functionality. And I `Cmd+Shift+P` and restarted their service. So we need something similar here as well because this forces me to continue the while VSCode to get it back.

**Comment by bradlc** [comment] 2023-01-27 09:52
Hey @hakobpogh. I'm going to close this because without a reproduction unfortunately we're not going to be able to get to the root of the problem. Sorry, I hope that's understandable! If other popular and built-in extensions have the same issue then perhaps there's something else going on here.

I think having a restart command is a good idea, I will look into that! In the meantime you can always use the `Developer: Restart Extension Host` command which should reset everything in one go.

**Closed by bradlc** 2023-01-27 09:52 UTC
