### ISSUE TITLE
How to use plugin with cdn

### ISSUE THREAD

**Issue by crrack** [tailwindlabs/tailwindcss-intellisense#195] opened 2020-09-20 15:47 UTC
Hi,
I sometime using tailwind only with cdn. Is it possible to active plugin, because I don’t have any tailwind.config.js.
Thanks for any help.

**Comment by lewishowles** [comment] 2020-10-14 15:38
I'm in a similar position. Our Tailwind CSS is built as part of a library, that can then be imported, meaning there's a central repository for the config and any custom CSS we've added to that. That means our projects don't have Tailwind installed, and have no Tailwind config.

But I really miss being able to use the intellisense here. Is it possible to have a way to run off a default config if no Tailwind is found?

**Comment by michaelmang** [comment] 2020-10-19 20:52
I am running into the same problem.

I consume a separate package in my app that combines my company's design stylesheet and tailwind. Because of this, the IntelliSense doesn't pick up the Tailwind dependency. Maybe there is a way to update the `package.json` that is used to resolve the config and confirm the dependency: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/src/class-names/resolveConfig.js#L8

**Comment by crrack** [comment] 2020-10-19 20:57
For me it´s not problem have in settings hard ON and have it ON in all projects.

**Comment by bradlc** [comment] 2020-12-01 12:02
Duplicate of #27

**Closed by bradlc** 2020-12-01 12:02 UTC

**Comment by caamillo-athomos** [comment] 2023-09-25 12:58
This is not a duplicate.
How can I use tailwindcss/plugin using tailwind's cdn?

**Comment by iambasantarai** [comment] 2024-03-06 14:35
> This is not a duplicate. How can I use tailwindcss/plugin using tailwind's cdn?

You can use the first-party plugins by using the plugins query parameter as described in [documentation](https://tailwindcss.com/docs/installation/play-cdn). 

Your `cdn` script may look like: 

```
  <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
```
