### ISSUE TITLE
Neovim LSP should work with standalone CLI, not requireing npm install

### ISSUE THREAD

**Issue by andradei** [tailwindlabs/tailwindcss-intellisense#972] opened 2024-05-25 15:45 UTC
**What version of VS Code are you using?**

Neovim 0.10.0

**What version of Tailwind CSS IntelliSense are you using?**

I think it's not applicable in neovim

**What version of Tailwind CSS are you using?**

v3.4.3

**What package manager are you using?**

npm - although this shouldn't be needed

**What operating system are you using?**

Linux (Arch-based)

**Tailwind config**

```js
import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography"

const config: Config = {
  content: ["./templates/**/*.html", "./public/**/*.js"],
  theme: {
    extend: {},
  },
  plugins: [forms, typography],
};

export default config;
```

**VS Code settings**

Not applicable, using neovim

**Reproduction URL**

Also not applicable

**Describe your issue**

I don't know if this should be a bug report or a feature request.

A standalone CLI tool is provided for projects that would use `npm` and have `package.json` only [because of Tailwind](https://tailwindcss.com/blog/standalone-cli#which-cli-should-i-use).

(screenshot for reference)
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/2653546/13b35c45-caec-49a2-b2c1-018139bc44d7)

But if I'm on neovim and want to use the [tailwincss-language-server](https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-server), looks like the only way to get it working is with `npm i -D tailwindcss`, which is contradictory to statement on the link above.

It would be great if the LSP server could optionally use the standalone CLI `tailwindcss` tool.

**Comment by andradei** [comment] 2024-05-25 15:53
Might be related to some of the confusion with getting things working as mentioned in #815

**Comment by thecrypticace** [comment] 2024-05-26 02:30
Working with a **specific version** of the standalone CLI isn't really possible right now. This is because we rely on loading internals from the filesystem to actually perform the necessary operations. The Standalone CLI is intended as just a CLI.

Having said that, you don't actually need to use the standalone CLI or an npm install to actually use the extension. We'll detect a Tailwind v3 project just fine — but you'll get the version of Tailwind that's bundled into the extension rather than whatever version is related to your CLI.

If that particular feature isn't working for you could you please provide a reproduction?

**Comment by thecrypticace** [comment] 2024-05-26 02:35
Having said that, I'd love to find some way to change this in v4. Possibly by building the language server (or some kind of other interface) into the CLI itself. I don't know what that'll look like though and I'm not sure if that'll happen for v4.0 (but perhaps a later 4.x release). It's also complicated by the fact that, right now, we still support Tailwind projects all the way back to v0.x.

**Comment by andradei** [comment] 2024-05-29 01:44
> Having said that, you don't actually need to use the standalone CLI or an npm install to actually use the extension. We'll detect a Tailwind v3 project just fine — but you'll get the version of Tailwind that's bundled into the extension rather than whatever version is related to your CLI.

That's a great feature. I don't know why it doesn't work for me in neovim. Maybe there are extra settings I need to set on the LSP client. Other people were already working on JS projects and did `npm i tailwindcss` to have it work as well (didn't have to install the standalone CLI, obviously). So wish I could give more details.

I'll keep an eye on v4 in case it improve this specific experience.

**Comment by thecrypticace** [comment] 2024-06-04 15:10
We've tested this locally with Neovim and the fallback version _is_ working in Neovim, VSCode, and Zed so it might be something specific to your setup. If you're able to provide a bit more detail (configuration, vim plugins, project structure, etc…) I'll look into it but I'm gonna close this one for now.

**Closed by thecrypticace** 2024-06-04 15:10 UTC
