### ISSUE TITLE
Support custom tag with React

### ISSUE THREAD

**Issue by dev-cyprium** [tailwindlabs/tailwindcss-intellisense#393] opened 2021-08-20 19:04 UTC
Hello, 

At the codebase I'm working on, instead of `className` we write `k` and the auto-suggestion popup doesn't happen. 
```
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true,
  },
```

Essentially when I've tried:
```
<Component k="(cmd+space)">
```

It shows "No suggestions", but works with `className`

It works for `className` but doesn't for `strings`, or like the question implies the `k` attribute. Can we add support for custom attributes when this triggers? Or am I missing something with the editor itself?

**Comment by bradlc** [comment] 2021-09-10 13:42
Duplicate of #350

**Closed by bradlc** 2021-09-10 13:42 UTC
