### ISSUE TITLE
Tailwindcss intellisense (auto-fill, auto-complete) not showing in vscode on macos with m1 suddenly.

### ISSUE THREAD

**Issue by Jazzykhan** [tailwindlabs/tailwindcss-intellisense#951] opened 2024-04-09 19:17 UTC
**What version of Tailwind CSS are you using?**

"autoprefixer": "^10.0.1",
"postcss": "^8",
"tailwindcss": "^3.3.0"

**What build tool (or framework if it abstracts the build tool) are you using?**

 "next": "14.1.4",

**What version of Node.js are you using?**

20.12.1

**What browser are you using?**

Chrome macos, m1

**What operating system are you using?**

Macos on Mac pro m1 2020

**Reproduction URL**

https://github.com/Jazzykhan/my-app

**Describe your issue**

I was always able to use tailwindcss intellisense on macos vscode from the start. now 2 days ago suddenly my tailwindcss intellisense stopped working. now after creating a brand new nextjs project with app dir. When the project run in any div when i type any tailwind property it doesnt show me auto-fill auto-complete option. I have even completly re-installed my macos for this issue i am very fraustating right now. A friend of mine told me to installed the tailwindcss extension on vscode but i have never used it before.In the past it always by default had shown me auto-fill/complete when i start typing anything in the className of div or any element.
See the screeshots please. Also with tailwindcss no auto-import or auto-fill is showing in my vs code.

<img width="1051" alt="Screenshot 2024-04-10 at 00 14 58" src="https://github.com/tailwindlabs/tailwindcss/assets/31903098/d604ef3b-7aa2-459b-aa5b-e506ca819feb">
<img width="1432" alt="Screenshot 2024-04-10 at 00 15 12" src="https://github.com/tailwindlabs/tailwindcss/assets/31903098/92866b05-cc03-4140-ae95-c426d1664dcf">

**Comment by thecrypticace** [comment] 2024-04-09 21:26
I'm not seeing any issues with your project using either the latest release or latest pre-release of the extension. Can you provide some more details about your VSCode installation like what version you're on and list of installed extensions?

You can get those by running these commands from the CLI if you have it installed:
```
code --version
```

```
code --list-extensions --show-versions
```

**Comment by Jazzykhan** [comment] 2024-04-09 22:05
Installed Vscode from the website for Macbook pro m1


Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:09.495Z (6 days ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.0.0


Extentions:

prettier and nothing else.

**Comment by thecrypticace** [comment] 2024-04-11 17:05
Two questions:
1. Are you sure the Tailwind CSS Intellisense extension is installed? If so what version is installed?
2. If it is can you update to the pre-release version and run "Tailwind CSS: Show Output" from the VSCode command palette and paste the output here?

**Comment by Jazzykhan** [comment] 2024-04-11 18:48
@thecrypticace  Hi, i didn't install the extension ever before and suggestions always worked before in my vscode. But now i have installed the extension to make the suggestions work and also it doesnt suggest if i type p-20 it shows p-1 when i type p- so i have to press my down arrow lol

**Comment by thecrypticace** [comment] 2024-04-11 23:21
The extension must to be installed to provide suggestions for Tailwind classes. The best you could get without installing our extension is existing, used classes from VSCode's own CSS intellisense.

But if it's working for you now then that's good. 👍 

> it doesn't suggest if i type p-20

It should at show p-20, px-20, and a few others. Can you provide a screenshot (or better, a video) of what you're seeing?

**Comment by thecrypticace** [comment] 2024-04-15 20:41
Gonna go ahead and close this one since the extension appears to be working as designed but if you see something not working that you think should please open another issue.

**Closed by thecrypticace** 2024-04-15 20:41 UTC
Labels: question
