### ISSUE TITLE
Cannot read properties of undefined (reading 'tailwindCSS') with commit ff52e815b6ba6a968a47453d4353597db3f14f63

### ISSUE THREAD

**Issue by polyzen** [tailwindlabs/tailwindcss-intellisense#459] opened 2022-01-08 02:54 UTC
**What version of Tailwind CSS IntelliSense are you using?**

0.7.5

**What version of Tailwind CSS are you using?**

2.2.19

**What package manager are you using?**

Self-built/npm

**What operating system are you using?**

Arch Linux

**Reproduction URL**

Can look into this if needed.

**Describe your issue**

In nvim-lsp, the following error points [here](https://github.com/tailwindlabs/tailwindcss-intellisense/commit/ff52e815b6ba6a968a47453d4353597db3f14f63#diff-77e2c85400db1d689fea4174d5857547d2a96630822c760e663fb307a033cb4cR257):
`Unhandled exception: Cannot read properties of undefined (reading 'tailwindCSS')\nTypeError: Cannot read properties of undefined (reading 'tailwindCSS')`

When looking at `server.ts`, tsserver seems to navigate to the definition of `tailwindCSS` just fine.

The server built from the commit prior to that works as expected.

Edit: To be clear 0.7.5 did not work for me in nvim-lsp.

**Comment by kabouzeid** [comment] 2022-01-12 15:22
Can confirm. It happens because apparently this server doesn't process the `workspace/didChangeConfiguration` (aka `onUpdateSettings()`) message before accessing `state.editor.globalSettings.tailwindCSS.files.exclude`. I've confirmed through the logs that the client already sent `workspace/didChangeConfiguration` before the server throws this error.

**Comment by bradlc** [comment] 2022-01-17 14:24
This should be fixed in `v0.7.6` 👍

**Closed by bradlc** 2022-01-17 14:24 UTC

**Comment by kabouzeid** [comment] 2022-01-17 15:14
It works now, but `tailwindCSS.files.exclude` must still be set in settings, i.e. not null.

thanks @bradlc

**Comment by kabouzeid** [comment] 2022-01-17 15:36
This didn't do the trick https://github.com/tailwindlabs/tailwindcss-intellisense/commit/08927cb7583784e402c8a872881dfc70d195e261 . What I meant is that the server is still crashing when `tailwindCSS.files.exclude` is not set.

```
 "Unhandled exception: Cannot read properties of undefined (reading 'exclude')\nTypeError: Cannot read properties of undefined (reading 'exclude')\n    at /usr/bin/tailwindcss-language-server:57:394882\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/bin/tailwindcss-language-server:57:394513)"
```

**Comment by bradlc** [comment] 2022-01-17 15:42
@kabouzeid Yeah that commit is unrelated to what you said. You're right though, the `files` config was still required. The latest commit should fix that 👍

**Comment by kabouzeid** [comment] 2022-01-17 15:45
jup, it's working now. thanks again!
