### ISSUE TITLE
variantsValue is not iterable

### ISSUE THREAD

**Issue by harshgour** [tailwindlabs/tailwindcss-intellisense#364] opened 2021-07-02 10:46 UTC
This is what I wrote in tailwind.config.js and it gave error variantsValue is not iterable. And then even if I remove the extend, it still shows an error. Intellisense is not working due to this issue.

<img width="337" alt="Screenshot 2021-07-02 at 4 15 14 PM" src="https://user-images.githubusercontent.com/60436404/124263298-b4ac7600-db50-11eb-8e5f-54437c59e593.png">

**Comment by bradlc** [comment] 2021-07-05 11:30
Hey. Which version of `tailwindcss` are you using? Which version of Tailwind CSS IntelliSense? What is your full Tailwind config? Does it work if you reload the VS Code window (for example by running the `Developer: Reload Window` command)?

**Comment by harshgour** [comment] 2021-07-06 20:01
My version of tailwind as specified in package.json is "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.4".

My tailwind config is =>
`module.exports = {
	purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
	darkMode: false, // or 'media' or 'class'
	theme: {
		extend: {
			screens: { xs: { max: "400px" } },
			fontSize: {
				main: ["80px", "83px"],
				mobMain: ["30px", "33px"],
				smMobMain: ["20px", "23px"],
				tabMain: ["60px", "63px"],
			},
			inset: { 84: "22rem", 22: "5.5rem", 18: "4.5rem" },
			borderWidth: {
				1: "1px",
				12: "12px",
			},
			colors: {
				logo: {
					primary: "#000",
				},
				text: {
					primary: "#292929",
					secondary: {
						"8d": "#8D8D8D",
					},
				},
				green: {
					neon: "#73f9d9",
				},
			},
			keyframes: {
				slideIn: {
					"0%": { transform: "translateX(calc( 100% + 10px ))" },
					"100%": { transform: "translateX(0px)" },
				},
				slideOut: {
					"0%": { transform: "translateX(0px)" },
					"100%": { transform: "translateX(calc( 100% + 10px ))" },
				},
			},
			animation: {
				slideIn: "slideIn .1s linear 1",
				slideOut: "slideOut .1s linear 1",
			},
			fill: (theme) => ({
				neon: theme("colors.green.neon"),
			}),
			borderColor: (theme) => ({ neon: theme("color.green.neon") }),
		},
	},
	variants: {
		extend: {
			fill: ["hover", "focus", "group-hover"],
			display: ["group-hover"],
		},
	},
	plugins: [],
};
`

The version of Tailwind CSS Intellisense used is v0.6.13.
It does not work when I reload VS Code window but it works when I uninstall and reinstall the Extension. But that also stops working after few runs.

**Comment by bradlc** [comment] 2021-09-17 11:37
Hey @harshgour. Are you able to share a GitHub repository that reproduces the issue?

**Comment by bradlc** [comment] 2022-01-17 17:45
I was not able to reproduce this using the config alone, and I'm going to close this as a full reproduction has not been provided. Please open a new issue (and answer the questions in the new issue template) if you're still having problems 👍

**Closed by bradlc** 2022-01-17 17:45 UTC
