### ISSUE TITLE
Intellisense stopped working in 0.9.5

### ISSUE THREAD

**Issue by shikhr** [tailwindlabs/tailwindcss-intellisense#697] opened 2023-01-13 13:11 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.5

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

npm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
   content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

```
Since updating to 0.9.5, intellisense stopped working entirely. Rolling back to 0.9.4 fixes the issue. To reproduce the bug:
1. Create a new vite app `npm create vite@latest`.
2. Add tailwind css to the project as instructed in the [docs](https://tailwindcss.com/docs/guides/vite).
3. Intellisense fails to work.
4. After rolling back to 0.9.4, everything starts working as normal.

**Comment by bradlc** [comment] 2023-01-13 13:18
Hey @shikhr. Please provide the following as requested in the issue template:

- VS Code settings in JSON format
- Reproduction URL: A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Comment by shikhr** [comment] 2023-01-13 13:43
@bradlc,
When I updated it back to 0.9.5 in order to create a new reproduction of the issue, it started working again. I checked, and it also started working in my original project as well. Sorry to bother you. I guess we can close the issue since the problem doesn't exist anymore?

**Comment by bradlc** [comment] 2023-01-13 14:54
Ah cool, yeah I'll close this then 👍

**Closed by bradlc** 2023-01-13 14:54 UTC
