### ISSUE TITLE
Intellisense without npm/node setup (e.g. CDN-only)

### ISSUE THREAD

**Issue by bradleypeabody** [tailwindlabs/tailwindcss-intellisense#157] opened 2020-07-26 20:51 UTC
I am experimenting with writing a [Vugu](https://vugu.org) application using Tailwind and it would be great to get the code-completion features without having to do create a separate npm setup that is only used for this VSCode plugin.

For now I am using the CDN link to https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css and initially I don't need any component extraction or other features.  I'm just trying to get code completion so I can hammer out some screens and get a feel for how this works.  (If this works out well I plan on later exploring the idea of further Tailwind integration with Vugu - there are a lot of aspects that might play well together.)

Any suggestions?

**Comment by johncarter-** [comment] 2020-07-29 07:45
I came searching for the same thing.

There's a few already closed issues about this: https://github.com/tailwindlabs/tailwindcss-intellisense/issues?q=cdn

It doesn't seem like it is possible at the moment, but would love to know if you get it working.

**Comment by bradleypeabody** [comment] 2020-07-29 14:04
For now, I ended up just following the instructions and installing the npm package and config and then adding the corresponding files to my `.gitignore`.  This works well enough for the simple cases I've tried so far.

**Comment by bradlc** [comment] 2020-08-12 15:23
Duplicate of #27

**Closed by bradlc** 2020-08-12 15:23 UTC
