### ISSUE TITLE
Not working when a tailwind config on typescript

### ISSUE THREAD

**Issue by UniqueNickname** [tailwindlabs/tailwindcss-intellisense#384] opened 2021-08-08 12:52 UTC
Tailwind working with tailwind.config.ts but the vscode extension doesn't see config.

![image](https://user-images.githubusercontent.com/48050888/128632587-0de493c9-3356-434c-8b88-00a42125a5b1.png)

![image](https://user-images.githubusercontent.com/48050888/128632567-aa2bcc08-9f27-4d28-9970-d6be641cd894.png)

**Comment by bradlc** [comment] 2021-08-13 12:48
Duplicate of #348

**Closed by bradlc** 2021-08-13 12:48 UTC
