### ISSUE TITLE
Getting duplicate entries after long delay in intellisense

### ISSUE THREAD

**Issue by sergio101** [tailwindlabs/tailwindcss-intellisense#326] opened 2021-05-16 06:38 UTC
I am new to VSCode, so I am trying to give as much input as possible.
- MacOS 11.3
- Phoenix 1.5.8
- Tailwindcss - 2.1.2
- Webpack 4.4.0
- Plugin Version v0.6.3
- VSCode Version: 1.56.2

I am having the issue: while editing the class, I don't see any completions for a long time. Then, after a while, I get completions, but there are several dupes. There are several pages of these dupes.

Hopefully, I can give enough info to be useful. Let me know if you need more info. Thanks!

<img width="604" alt="image" src="https://user-images.githubusercontent.com/77505/118387924-3bcc7b80-b5ef-11eb-8877-087f11ff809e.png">

<img width="597" alt="image" src="https://user-images.githubusercontent.com/77505/118387968-8bab4280-b5ef-11eb-8e8b-2a7bd105e9e0.png">

**Comment by sergio101** [comment] 2021-05-16 06:52
Just out of curiosity, I installed version v0.5.10 of the plugin, and it works fine.

**Comment by bradlc** [comment] 2021-05-17 11:57
Duplicate of #316. Please read [my comment over there](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/316#issuecomment-842264450).

**Closed by bradlc** 2021-05-17 11:57 UTC
