### ISSUE TITLE
TypeScript support ? :-)

### ISSUE THREAD

**Issue by gekkedev** [tailwindlabs/tailwindcss-intellisense#413] opened 2021-09-21 11:57 UTC
After renaming my Tailwind config from `tailwind.config.js` to `tailwind.config.ts`, the extension doesn't work that well anymore even though the file is present under a slightly altered name (throws`No config file found`). However, the IntelliSense functionality can still be triggered though, but requires you to explicitly press CTRL+space.
https://github.com/tailwindlabs/tailwindcss-intellisense/blob/8fce24db9c480a9615e175fb3acaac91f7a0a7c1/packages/tailwindcss-intellisense/src/class-names/index.js#L30
My suggestion is to add `.ts` as a file ending here (are there others we might add as well?) because any valid JS is valid TS and possibly there will be better typing support in the future of TWCSS.
If you would accept a PR of this kind, let me know and I'll gladly create one which also updates the documentation.

**Comment by bradlc** [comment] 2021-09-24 14:44
Duplicate of #348

**Closed by bradlc** 2021-09-24 14:44 UTC
