### ISSUE TITLE
Without Tailwind Install

### ISSUE THREAD

**Issue by AverTry** [tailwindlabs/tailwindcss-intellisense#355] opened 2021-06-23 15:34 UTC
Awesome new JIT client, but intellisense needs tailwind installed ?
I installed, removed the dependency info from package.json and it still works. 
So installed Tailwind globally and Intellisense fails to work.

Is it possible to have what intellisense needs included with the plugin, Or allow it to see tailwind Globally.
WHY: Because on small projects, having 50MB extra per backup for the node folder seems silly now with the way JIT runs.

Thank you For a Great Tool.

**Comment by bradlc** [comment] 2021-07-07 11:20
Hey @AverTry. Going to close this as it is a duplicate of #27. I want to look into supporting this use-case at some point 👍

**Closed by bradlc** 2021-07-07 11:20 UTC
