### ISSUE TITLE
Couldn't show SCSS/CSS suggestions because of @screen

### ISSUE THREAD

**Issue by arekuusa** [tailwindlabs/tailwindcss-intellisense#438] opened 2021-11-30 08:45 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.2

**What version of Tailwind CSS are you using?**

2.2.19

**What package manager are you using?**

npm, gulp

**What operating system are you using?**

Windows 10

Reproduction URL

none

Describe your issue

Couldn't show SCSS / CSS suggestions because of @screen http://joxi.ru/52aND3KuE1j5zA
Works to show SCSS / CSS suggestions without @screen http://joxi.ru/823nXDws9Rvd1m

Waiting for an answer

**Comment by arekuusa** [comment] 2021-12-14 10:59
Anyone have an answer?

**Comment by bigmike36c** [comment] 2021-12-29 18:43
I'm having similar issues as detailed in #428. However, since I solved the directive highlighting issue with an extension, I closed #428 and wanted to consolidate the feedback in regards to issues with hover information and intellisense suggestions when using @screen.

Normal Property Hover Behavior:
![image](https://user-images.githubusercontent.com/81941044/147693192-e4c59e0b-9602-4e36-aef2-94aace24cef7.png)

No Hover Information Inside @screen Directive:
![image](https://user-images.githubusercontent.com/81941044/147693215-addbc3b1-0fc0-49ad-8b39-72a50de96e4e.png)

No Hover Information on @screen Directive:
![image](https://user-images.githubusercontent.com/81941044/147693199-ffe361f3-4781-4a7f-85d5-d30146ac26df.png)

Additionally, some autocomplete options appear when typing but is limited to "Text" autocompletion as opposed to the "Properties and Attributes" or "Constants" autocompletion (vscode defines [types of completions here](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions)) you would typically see in a standard .css/.scss files (for properties and attributes) or an .html file (for tailwind class constants). The difference is shown below:

Normal Properties and Attributes Autocomplete in .css/.scss Files:
![image](https://user-images.githubusercontent.com/81941044/147693392-bd6b90f5-0666-4c22-9d8a-1fc9b5639a00.png)

Normal Tailwind Constants Autocomplete in .html Files:
![image](https://user-images.githubusercontent.com/81941044/147693413-7355d80d-741a-4384-bc62-3e715eefdd40.png)

Unexpected Text Autocomplete in .css/.scss Files:
![image](https://user-images.githubusercontent.com/81941044/147693426-6fa2fd9e-387c-478a-8ed7-a306c5d6f38a.png)

Finally, this issue is not present when using @apply in .css/.scss files leading me to believe that perhaps we can not use the @screen directive with standard CSS. Can anyone confirm?

![image](https://user-images.githubusercontent.com/81941044/147693446-d07ddab3-aa34-4543-8320-82471611f5bd.png)

**Comment by bigmike36c** [comment] 2021-12-30 22:21
I wanted to post a quick workaround for anyone who stumbles across this issue. You can replace `@screen xl` with `@media (min-width: theme('screens.xl'))` to provide suggestions with standard css/scss. Obviously much more verbose, but this allows you to continue to use the tailwind.config to control breakpoints while maintaining intellisense functionality.

**Comment by arekuusa** [comment] 2022-01-04 07:41
Thanks for the answer. It is possible to replace @screen xl with @media (min-width: theme('screens.xl')).

**Comment by bigmike36c** [comment] 2022-01-05 01:40
@arekuusa Even with the workaround, I would consider leaving this issue open until a maintainer can confirm that behavior we experienced is the intended behavior.

**Comment by arekuusa** [comment] 2022-01-05 07:12
Okay, for now, leave it open

**Comment by bradlc** [comment] 2022-02-15 22:51
Hey @arekuusa. I am unable to view your `joxi.ru` links, but I think I understand the problem, and it's the same as #253: CSS IntelliSense does not work when nested inside Tailwind at-rules (e.g. `@screen`, `@layer`). I'm going to close this issue in favour of that one.

**Closed by bradlc** 2022-02-15 22:51 UTC

**Comment by arekuusa** [comment] 2022-02-16 11:43
Hey @bradlc , I changed the links to pictures. Look here please.
I read #253. Is the @screen directive not highlighted when using SCSS?
