### ISSUE TITLE
ESM Syntax causing extension to not work.

### ISSUE THREAD

**Issue by buffet-time** [tailwindlabs/tailwindcss-intellisense#618] opened 2022-10-02 00:19 UTC
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.8.7

**What version of Tailwind CSS are you using?**

For example: v3.1.8

**What package manager are you using?**

PNPM 7.12.2

**What operating system are you using?**

Windows 11 Pro latest

**Reproduction URL**

N/A

**Describe your issue**

I recently rewrote my PostCSS and Tailwind configs to be of ESM style instead of CJS requires() this does work at build time and whatnot, but the intellisense engine fails. I know it's reccomended to do CJS but since potscss and Tailwind are both working in this ESM context I don't see why the extension shouldn't also.

```
Found Tailwind CSS config file: e:\Programming\musicChartSite\tailwind.config.js
Loaded postcss v8.4.16: E:\Programming\musicChartSite\node_modules\.pnpm\postcss@8.4.16\node_modules\postcss
Loaded tailwindcss v3.1.8: E:\Programming\musicChartSite\node_modules\.pnpm\tailwindcss@3.1.8_postcss@8.4.16\node_modules\tailwindcss
[Error - 8:19:59 PM] Tailwind CSS: require() of ES Module e:\Programming\musicChartSite\tailwind.config.js from c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js not supported.
Instead change the require of tailwind.config.js in c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module e:\Programming\musicChartSite\tailwind.config.js from c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js not supported.
Instead change the require of tailwind.config.js in c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js to a dynamic import() which is available in all CommonJS modules.
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at _require.cs.default.require (c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:179:63908)
    at c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:693:9787
    at Generator.next (<anonymous>)
    at c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:1:1201
    at new Promise (<anonymous>)
    at zt (c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:1:1021)
    at v (c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:693:8732)
    at c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:693:3566
    at Generator.next (<anonymous>)
    at c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:1:1201
    at new Promise (<anonymous>)
    at zt (c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:1:1021)
    at x (c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:693:3531)
    at c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:693:8706
    at Generator.next (<anonymous>)
    at i (c:\Users\radd8\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.7\dist\tailwindServer.js:1:1059)

```

**Comment by bradlc** [comment] 2022-10-03 08:54
Duplicate of #565 #592

**Closed by bradlc** 2022-10-03 08:54 UTC
