### ISSUE TITLE
Error on VS Code lint

### ISSUE THREAD

**Issue by wrtisans** [tailwindlabs/tailwindcss-intellisense#137] opened 2020-06-26 18:32 UTC
i'm having this error with vscode and phpstorm devtools 

`Saving 'PaymentsController.php': Getting code actions from ''Tailwind CSS IntelliSense', 'PHP Tools for VS Code''`

this error only happens on .php files

**Comment by bradlc** [comment] 2020-06-29 11:57
Please can you provide a bit more information @wrtisans? That doesn’t look like an error to me. Is something not working?

**Comment by praburangki** [comment] 2020-08-16 14:00
I often see this popup and I agree I believe it's not an error.
But my issue is sometimes while saving a file this popup appears and I have to wait 2-10 seconds for the file to actually being saved. In the popup it is shown that it's getting code actions from `Vetur, Tailwind CSS Intellisense, stylelint, eslint`.
It's hard to reproduce because it's intermittent. I've tried to disable this extension and it's seems it is working smoothly.

**Comment by bradlc** [comment] 2021-01-08 16:23
Going to close this as it isn't clear whether this is an issue with the extension. Feel free to open a new issue if you think that is the case and can reproduce it though, thank!

**Closed by bradlc** 2021-01-08 16:23 UTC
Labels: question
