### ISSUE TITLE
autocomplete not showing on laravel blade project. I also have tried the troubleshooting that you've been suggesting but still wont work.. But the autocomplete works just fine with simple .html 

### ISSUE THREAD

**Issue by jamez00** [tailwindlabs/tailwindcss-intellisense#476] opened 2022-02-08 09:06 UTC
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.0

**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What package manager are you using?**

For example: npm, yarn

**What operating system are you using?**

For example: macOS, Windows

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by bradlc** [comment] 2022-02-15 23:01
Hey @jamez00. Do you have an extension installed that provides Laravel Blade support, and if so which one?

Also if you could provide a reproduction repository as per the issue template that would be great!

**Comment by bradlc** [comment] 2022-02-23 14:03
I'm going to close this because the issue template was not filled out. If you're still having issues please open a new issue with a proper reproduction — a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand. Additionally, if you could provide the following information that would be great:

- A list of installed extensions (run `code --list-extensions --show-versions` if you have the `code` command installed)
- Your VS Code settings in JSON format (run `Preferences: Open Settings (JSON)` command within VS Code)

**Closed by bradlc** 2022-02-23 14:03 UTC
