### ISSUE TITLE
Can't autocomplete with custom class.

### ISSUE THREAD

**Issue by MichealXie** [tailwindlabs/tailwindcss-intellisense#403] opened 2021-09-03 06:26 UTC
I add some class in tailwind.css, but i can't get autocomplete in tsx while other .js file generated class can be autocompleted nicely.

#### Plugin is run well, without error.
<img width="1271" alt="截屏2021-09-03 下午2 29 48" src="https://user-images.githubusercontent.com/27472703/131960489-ed895fd7-e1ab-4101-9f2b-ed5e0d3caef3.png">

#### tailwind.dist.css are generated successfully, I can see the class.

<img width="692" alt="截屏2021-09-03 下午2 29 20" src="https://user-images.githubusercontent.com/27472703/131960447-59dfcbc4-8567-408d-86da-8148b6f8fa23.png">

<img width="1055" alt="截屏2021-09-03 下午2 28 00" src="https://user-images.githubusercontent.com/27472703/131960311-876e8827-d918-4517-b794-51f635df2dd6.png">

<img width="824" alt="截屏2021-09-03 下午2 25 32" src="https://user-images.githubusercontent.com/27472703/131960189-6cfe4ac1-23aa-4771-8957-c862c7cb1383.png">

**Comment by bradlc** [comment] 2021-09-03 12:22
Hey @MichealXie. The extension does not currently handle custom CSS at all. Maybe one day it will! Duplicate of #227

**Closed by bradlc** 2021-09-03 12:22 UTC
