### ISSUE TITLE
Intellisense does not work with VSCode Remote Repositories

### ISSUE THREAD

**Issue by ooliver1** [tailwindlabs/tailwindcss-intellisense#398] opened 2021-08-25 21:27 UTC
So I've installed and tried to use tailwindcss intellisense with my remote repository set-up, show output is on and says no config found if I remove the config file but with it the extension cancels loading in extension host logs. 

All latest updates, 

```Windows 10 20H2
Version: 1.59.1 (user setup)
Commit: 3866c35
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by PudparK** [comment] 2021-09-02 23:51
Having the same issue.
NextJS

**Comment by f00f** [comment] 2021-09-15 15:00
Similar issue here. My workspace is in the WSL 2 linux file system.
I open the folder `\\wsl$\<distro>\home\<user>\<workspace>\` in Windows Explorer and then select "Open in VS Code" in the context menu.

Error message:

```
[Error - 16:59:26] Tailwind CSS: ENOENT: no such file or directory, open '/wsl$/<etc...>
```

I found that `normalize-path` in `server.ts : init()` changes the actual path to `/wsl$/<etc>` which is not valid on Windows.

**Comment by bradlc** [comment] 2021-09-17 14:10
Hey @ooliver1. The extension is not compatible with virtual filesystems, which is what Remote Repositories uses. I am going to publish an update which will just disable the extension completely in these circumstances. Sorry about that!

@PudparK @f00f WSL is not related to Remote Repositories as far as I'm aware. I am keen to look into any issues there though, so please open a new issue, ideally with a link to a project that has the error, thanks!

**Comment by SupunSam** [comment] 2021-09-17 15:31
> Hey @ooliver1. The extension is not compatible with virtual filesystems, which is what Remote Repositories uses. I am going to publish an update which will just disable the extension completely in these circumstances. Sorry about that!
> 
> @PudparK @f00f WSL is not related to Remote Repositories as far as I'm aware. I am keen to look into any issues there though, so please open a new issue, ideally with a link to a project that has the error, thanks!

But as many of us now moving into docker-based development this will be an issue clearly. Can we have anything else to do about this?

I maean in this case extension is looking for the following in the path from vs code:

'\wsl$'

But it should look for the '\\wsl$'

If you can fix that it will fix the issue. Or you can introduce a setting to do that. Some kind of a config file or something. Please don't disable it entirely for remotes. As a laravel developer, I know for a fact that many developers are migrating to docker based laravel sail from VMs. So this will be a huge blow to them if you disable it entirely for the remotes.

My Error:

`[Error - 11:01:52 AM] Tailwind CSS: ENOENT: no such file or directory, open '\wsl$\Ubuntu-20.04\home\supundev\LK-EATS-app\tailwind.config.js'
Error: ENOENT: no such file or directory, open '\wsl$\Ubuntu-20.04\home\supundev\LK-EATS-app\tailwind.config.js'`

**Comment by bradlc** [comment] 2021-09-17 15:42
@SupunSam Unless I am misunderstanding, this issue (#398) is regarding [Remote Repositories](https://code.visualstudio.com/blogs/2021/06/10/remote-repositories), which has nothing to do with WSL. Following [an update](https://github.com/tailwindlabs/tailwindcss-intellisense/commit/1bd1d0e504dbabfbf68077beadf642cb4eec5483) the extension will be disabled in **virtual workspaces**. Again, this is not related to WSL. The issue that you, @PudparK and @f00f are talking about is unrelated so please open a new issue with a reproduction. The extension works fine with WSL generally so I need to know more about your specific setup to be able to debug the issue. Hope that clears things up!

**Comment by SupunSam** [comment] 2021-09-18 03:45
Yes @bradlc . You are right. I got it wrong. Extremely sorry about the mistake. My concern is regarding WSL when we open the code folder via network path. it works fine when we open directly from WSL using teminal. 

Thank you very much for your explanation.

**Comment by f00f** [comment] 2021-09-20 07:04
I opened a new issue here: #411

**Comment by bradlc** [comment] 2021-09-29 16:06
Since `v0.6.15` the extension is now disabled within virtual workspaces as it does not currently support those. Going to close this in favour of #390

**Closed by bradlc** 2021-09-29 16:06 UTC

**Comment by zackha** [comment] 2023-02-15 11:32
If you are working with nuxt3, you can try this.

Add the following configuration to your `.vscode/settings.json file`, so that Tailwind directives have proper autocomplete, syntax highlighting, and linting:

```
"tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs"
"files.associations": {
    "*.css": "tailwindcss"
}
```

detailed: [link](https://tailwindcss.nuxt.dev/tailwind/editor-support)
