### ISSUE TITLE
VSCode Hangs indefinitely while Formatting on save since version 0.9.8

### ISSUE THREAD

**Issue by glekner** [tailwindlabs/tailwindcss-intellisense#755] opened 2023-04-03 10:18 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.8+

**What version of Tailwind CSS are you using?**

v3.2.7

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Tailwind config**

```js
/* eslint-disable unicorn/prefer-module */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['src/**/!(@generated)/*.{ts,tsx}', './index.html'],
  darkMode: ['class', `.bp3-dark`],
  theme: {
    extend: {
      colors: {
        primary: '#0254ec',
        foreground: '#ffffff',
        tint1: '#F9F9FB',
        tint2: '#F5F6F7',

        text: {
          default: '#222',
          muted: '#737376',
          disabled: '#A6B1BB',
        },

        border: {
          default: '#E4E7EB',
          muted: '#F5F6F7',
        },

        // dark theme colors
        dark: {
          foreground: '#0D1116',
          tint1: '#161B22',
          tint2: '#1c232b',

          text: {
            default: '#234361',
            muted: '#8C949E',
            disabled: '#535a63',
          },

          border: {
            default: '#30363D',
            muted: '#E4E7EB',
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms')({
      // disable base styles since it conflicts with blueprint css
      strategy: 'class',
    }),
  ],
  corePlugins: {
    // disable preflight since we use blueprint css normalization
    preflight: false,
  },
};
```

**VS Code settings**

```json
{
  "editor.fontFamily": "Jetbrains Mono, Copyright Klim Type Foundry, SF Mono,IBM Plex Mono, Consolas",
  "editor.inlineSuggest.enabled": true,
  "terminal.integrated.defaultProfile.osx": "fish",
  "terminal.integrated.defaultProfile.linux": "zsh",
  "terminal.integrated.fontSize": 12,
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "git.autofetch": true,
  "git.confirmSync": false,
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "redhat.telemetry.enabled": false,
  "editor.fontSize": 13,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "github.copilot.enable": {
    "*": true,
    "yaml": false,
    "plaintext": true,
    "markdown": false,
    "json": true
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "security.workspace.trust.untrustedFiles": "open",
  "editor.formatOnSave": true,
  "workbench.colorCustomizations": {
    "[Horizon Extended]": {
      "editor.background": "#1e252d",
      "tab.border": "#474a62a1",
      "panel.border": "#474a62a1",
      "sideBar.border": "#474a62a1",
      "titleBar.border": "#474a62a1",
      "panel.dropBorder": "#474a62a1",
      "activityBar.border": "#474a62a1",
      "menu.border": "#474a62a1",
      "terminal.border": "#474a62a1",
      "tab.activeBorder": "#98a4fc",
      "editorGroup.border": "#474a62a1",
      "activityBar.inactiveForeground": "#9f9cb2",
      "activityBar.foreground": "#d19fff",
      "scrollbarSlider.background": "#d6dbff3e"
    }
  },
  "editor.tokenColorCustomizations": {
    "[Night Wolf (dark blue)]": {}
  },
  "editor.minimap.enabled": false,
  "explorer.sortOrder": "type",
  "editor.guides.bracketPairs": "active",
  "[yaml]": {
    "editor.defaultFormatter": "redhat.vscode-yaml"
  },
  "terminal.integrated.enablePersistentSessions": false,
  "editor.cursorSmoothCaretAnimation": "on",
  "workbench.list.smoothScrolling": true,
  "git.mergeEditor": true,
  "editor.codeLensFontFamily": "Copyright Klim Type Foundry",
  "editor.inlayHints.fontFamily": "Copyright Klim Type Foundry",
  "helium-icon-theme.folders.color": "#90a4ae",
  "helium-icon-theme.folders.theme": "specific",
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1"
  },
  "editor.accessibilitySupport": "off",
  "debug.console.fontFamily": "Copyright Klim Type Foundry",
  "telemetry.telemetryLevel": "off",
  "oneDarkPro.italic": false,
  "breadcrumbs.symbolPath": "off",
  "window.commandCenter": true,
  "workbench.editor.autoLockGroups": {
    "jsProfileVisualizer.cpuprofile.table": true
  },
  "editor.fontLigatures": false,
  "editor.gotoLocation.multipleDefinitions": "goto",
  "editor.gotoLocation.multipleTypeDefinitions": "goto",
  "editor.foldingMaximumRegions": 10000,
  "turboConsoleLog.wrapLogMessage": false,
  "turboConsoleLog.logMessagePrefix": "",
  "turboConsoleLog.includeFileNameAndLineNum": false,
  "editor.stickyScroll.enabled": true,
  "mergeEditor.diffAlgorithm": "experimental",
  "yaml.customTags": [
    "!And",
    "!And sequence",
    "!If",
    "!If sequence",
    "!Not",
    "!Not sequence",
    "!Equals",
    "!Equals sequence",
    "!Or",
    "!Or sequence",
    "!FindInMap",
    "!FindInMap sequence",
    "!Base64",
    "!Join",
    "!Join sequence",
    "!Cidr",
    "!Ref",
    "!Sub",
    "!Sub sequence",
    "!GetAtt",
    "!GetAZs",
    "!ImportValue",
    "!ImportValue sequence",
    "!Select",
    "!Select sequence",
    "!Split",
    "!Split sequence"
  ],
  "extensions.experimental.useUtilityProcess": true,
  "editor.smoothScrolling": true,
  "githubPullRequests.notifications": "pullRequests",
  "remote.SSH.remotePlatform": {
    "sandbox.1vs96w.csb": "linux",
    "wiz-sec.wiz.develop.csb": "linux"
  },
  "eslint.alwaysShowStatus": true,
  "debug.javascript.autoAttachFilter": "disabled",
  "svelte.enable-ts-plugin": true,
  "svelte.plugin.svelte.note-new-transformation": false,
  "totalTypeScript.hideAllTips": false,
  "totalTypeScript.hideBasicTips": true,
  "totalTypeScript.hiddenTips": [
    "passing-generics-to-types",
    "non-null-expression",
    "keyof",
    "typeof",
    "record-utility-type",
    "partial-utility-type",
    "nonnullable-utility-type",
    "omit-utility-type",
    "returntype-utility-type",
    "generic-slots-in-functions"
  ],
  "githubPullRequests.pullBranch": "never",
  "settingsSync.ignoredSettings": ["terminal.integrated.fontFamily"],
  "terminal.integrated.fontFamily": "Jetbrains Mono,SF Mono, Consolas, Copyright Klim Type Foundry",
  "terminal.integrated.persistentSessionReviveProcess": "never",
  "workbench.iconTheme": "bearded-icons",
  "workbench.colorTheme": "GitHub Dark",
  "git.openRepositoryInParentFolders": "never",
  "workbench.productIconTheme": "fluent-icons",
  "editor.letterSpacing": -0.2,
  "terminal.integrated.smoothScrolling": true
}

```

**Reproduction URL**

no need

**Describe your issue**
<img width="491" alt="image" src="https://user-images.githubusercontent.com/24938324/229519107-1c45b3f3-1fbf-4ccf-b75a-9161188b984d.png">

VSCode Hangs indefinitely while Formatting on save since version 0.9.8 and above.
This can start happening between 10-30 min after starting a coding session.
Disabling this extension solves the Issue, can you please take a look?

**Comment by bengry** [comment] 2023-04-03 17:26
I've had this issue as well, and after disabling `tailwindCSS.validate`, I think it's pretty much gone. So that's probably the root cause, not anything else in the extension.

**Comment by ptrxyz** [comment] 2023-04-10 12:45
yep, also observing this. can i simply downgrade until this is fixed?

**Comment by ptrxyz** [comment] 2023-04-10 18:40
@thecrypticace  Do you mean this one? https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
I am using it, version 9.10.4

**Comment by thecrypticace** [comment] 2023-04-10 19:25
That is the one I'm talking about yes. There've been reports of slowness regarding the tailwindcss prettier plugin inside VSCode which I'm investigating. I'm not certain yet if they're related. Just gathering data currently.

**Comment by bengry** [comment] 2023-04-10 19:29
> That is the one I'm talking about yes. There've been reports of slowness regarding the tailwindcss prettier plugin inside VSCode which I'm investigating. I'm not certain yet if they're related. Just gathering data currently.

I use that extension, but not the tailwind plugin for prettier. So I'm not sure that's related.

**Comment by thecrypticace** [comment] 2023-04-10 19:37
Ah that's good to know! Thanks!

**Comment by bradennapier** [comment] 2023-04-18 18:58
Also running into this.  At first i thought it was the custom regex rules but happens with vanilla settings too.

**Comment by valgeirb** [comment] 2023-04-18 19:49
Can we do something to help? This is driving me nuts.

**Comment by joneath** [comment] 2023-04-18 20:00
For those that are experiencing this, is your codebase a Vue app? Do you have the Volar extension installed? I first blamed the Tailwind plugin but removing it did not fix this issue. When viewing the locked up VS Code Extension Host process it's has a call chain starting with volar -> prettier -> tailwind. In the [Volar issues](https://github.com/vuejs/language-tools/issues?q=is:issue+is:closed) they have been reporting this bug as well and supposedly it's fixed in the most recent pre-release. 🤞

**Comment by bradlc** [comment] 2023-04-18 20:24
Hey all. I'm more than happy to take a look into this issue but it's going to be incredibly difficult without some more information. If somebody could share the following that would be a great help:

- A GitHub repository containing a project which can be opened in VS Code to reproduce the issue
- A list of all installed extensions (`code --list-extensions --show-versions`)
- All VS Code settings in JSON format

It would also be interesting to know what everyone is actually seeing when this is happening. Is everyone seeing the code actions message? And does it ever _only_ have Tailwind CSS IntelliSense listed? Or are there always other extensions mentioned?

@glekner, does the issue go away for you if you downgrade to `v0.9.7`?

**Comment by glekner** [comment] 2023-04-19 07:02
@bradlc I managed to reproduce the issue with `v0.9.7` now.
Not sure how to proceed here, could this be a combination with the `prettier` extension?
Anyway we can rule out the issue being coupled with `0.9.8`.

**Comment by fturmel** [comment] 2023-04-19 12:29
@bradlc I am experiencing this issue as well in a NextJS 13 and TypeScript codebase. I did see the code actions message too, both Tailwind CSS IntelliSense and ESLint were listed but will take screenshots next time.

<details><summary>VS Code extensions</summary>

- alefragnani.Bookmarks@13.3.1
- amiralizadeh9480.laravel-extra-intellisense@0.6.3
- Angular.ng-template@15.2.1
- astro-build.astro-vscode@0.28.2
- bierner.markdown-mermaid@1.18.1
- bmewburn.vscode-intelephense-client@1.9.5
- bowlerhatllc.vscode-as3mxml@1.16.0
- bowlerhatllc.vscode-nextgenas@2.0.0
- bowlerhatllc.vscode-swf-debug@1.6.1
- bpruitt-goddard.mermaid-markdown-syntax-highlighting@1.5.1
- bradlc.vscode-tailwindcss@0.9.11
- bungcip.better-toml@0.3.2
- clinyong.vscode-css-modules@0.4.2
- codingyu.laravel-goto-view@1.3.8
- csstools.postcss@1.0.9
- dbaeumer.vscode-eslint@2.4.0
- denoland.vscode-deno@3.17.0
- eamodio.gitlens@13.5.0
- ecmel.vscode-html-css@1.13.1
- EditorConfig.EditorConfig@0.16.4
- Equinusocio.vsc-community-material-theme@1.4.6
- Equinusocio.vsc-material-theme@33.8.0
- equinusocio.vsc-material-theme-icons@2.7.5
- esbenp.prettier-vscode@9.10.4
- formulahendry.auto-rename-tag@0.1.10
- GitHub.vscode-pull-request-github@0.62.0
- glitchbl.laravel-create-view@0.0.6
- golang.go@0.38.0
- GrapeCity.gc-excelviewer@4.2.57
- Gruntfuggly.todo-tree@0.0.226
- hangxingliu.vscode-systemd-support@1.0.1
- HTMLHint.vscode-htmlhint@1.0.4
- IHunte.laravel-blade-wrapper@1.0.1
- jock.svg@1.5.2
- mhutchie.git-graph@1.30.0
- mikestead.dotenv@1.0.1
- mquandalle.graphql@0.1.2
- ms-azuretools.vscode-docker@1.25.0
- ms-python.isort@2022.8.0
- ms-python.python@2023.6.1
- ms-python.vscode-pylance@2023.4.20
- ms-toolsai.jupyter@2023.3.1201040234
- ms-toolsai.jupyter-keymap@1.1.0
- ms-toolsai.jupyter-renderers@1.0.15
- ms-toolsai.vscode-jupyter-cell-tags@0.1.8
- ms-toolsai.vscode-jupyter-slideshow@0.1.5
- ms-vscode-remote.remote-containers@0.288.1
- ms-vscode-remote.remote-ssh@0.100.0
- ms-vscode-remote.remote-ssh-edit@0.84.0
- ms-vscode.cmake-tools@1.13.45
- ms-vscode.cpptools@1.14.5
- ms-vscode.cpptools-extension-pack@1.3.0
- ms-vscode.cpptools-themes@2.0.0
- ms-vscode.js-debug-nightly@2023.4.1317
- ms-vscode.live-server@0.4.7
- ms-vscode.remote-explorer@0.4.0
- mtxr.sqltools@0.27.1
- naoray.laravel-goto-components@1.2.0
- onecentlin.laravel-blade@1.34.0
- onecentlin.laravel-extension-pack@1.1.0
- onecentlin.laravel5-snippets@1.17.0
- pflannery.vscode-versionlens@1.5.0
- PKief.material-icon-theme@4.26.0
- pranaygp.vscode-css-peek@4.2.0
- Prisma.prisma@4.13.0
- quicktype.quicktype@12.0.46
- redhat.java@1.17.0
- REditorSupport.r@2.7.2
- rust-lang.rust-analyzer@0.3.1481
- ryannaddy.laravel-artisan@0.0.28
- samuelcolvin.jinjahtml@0.20.0
- shufo.vscode-blade-formatter@0.20.14
- stef-k.laravel-goto-controller@0.0.15
- svelte.svelte-vscode@107.3.0
- twxs.cmake@0.0.17
- Tyriar.sort-lines@1.9.1
- usernamehw.errorlens@3.10.0
- VisualStudioExptTeam.intellicode-api-usage-examples@0.2.7
- VisualStudioExptTeam.vscodeintellicode@1.2.30
- vscjava.vscode-java-debug@0.49.1
- vscjava.vscode-java-dependency@0.21.2
- vscjava.vscode-java-pack@0.25.10
- vscjava.vscode-java-test@0.38.2
- vscjava.vscode-maven@0.41.0
- WallabyJs.console-ninja@0.0.108
- webhint.vscode-webhint@2.1.9
- wholroyd.jinja@0.0.8
- xdebug.php-debug@1.32.1
- xdebug.php-pack@1.0.3
- yoavbls.pretty-ts-errors@0.2.8
- zamerick.vscode-caddyfile-syntax@1.0.4
- Zignd.html-css-class-completion@1.20.0
- zobo.php-intellisense@1.1.2

</details> 

<details><summary>VS Code user settings</summary>
<p>

```json
{
	"explorer.confirmDelete": false,
	"files.autoSave": "onFocusChange",
	"editor.renderWhitespace": "none",
	"editor.autoClosingBrackets": "always",
	"editor.autoClosingQuotes": "always",
	"window.restoreWindows": "all",
	"eslint.packageManager": "yarn",
	"npm.packageManager": "yarn",
	"javascript.updateImportsOnFileMove.enabled": "always",
	"explorer.confirmDragAndDrop": false,
	"editor.codeActionsOnSave": {
		"source.organizeImports": true,
		"source.fixAll.eslint": false
	},
	"workbench.colorTheme": "Material Theme Palenight High Contrast",
	"workbench.iconTheme": "material-icon-theme",
	"workbench.colorCustomizations": {},
	"editor.fontSize": 13,
	"git.autofetch": true,
	"[javascript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[html]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"typescript.updateImportsOnFileMove.enabled": "always",
	"[json]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[python]": {
		"editor.defaultFormatter": "ms-python.python",
		"editor.formatOnType": true
	},
	"versionlens.npm.caching.duration": 1,
	"versionlens.suggestions.showOnStartup": true,
	"[svelte]": {},
	"go.autocompleteUnimportedPackages": true,
	"go.useLanguageServer": true,
	"[go]": {
		"editor.defaultFormatter": "golang.go"
	},
	"[typescript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[typescriptreact]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"workbench.tree.indent": 16,
	"workbench.tree.renderIndentGuides": "always",
	"files.autoSaveDelay": 5000,
	"prettier.tabWidth": 4,
	"prettier.singleQuote": true,
	"prettier.printWidth": 120,
	"prettier.jsxSingleQuote": true,
	"prettier.arrowParens": "avoid",
	"[jsonc]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"prettier.trailingComma": "all",
	"files.associations": {
		"*.rmd": "markdown"
	},
	"workbench.editorAssociations": {
		"*.ipynb": "default"
	},
	"workbench.startupEditor": "newUntitledFile",
	"[c]": {
		"editor.wordBasedSuggestions": false,
		"editor.suggest.insertMode": "replace",
		"editor.semanticHighlighting.enabled": true
	},
	"[css]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"todo-tree.general.tags": ["BUG", "HACK", "FIXME", "TODO", "XXX", "[ ]", "[x]"],
	"todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)",
	"go.toolsManagement.autoUpdate": true,
	"workbench.panel.defaultLocation": "right",
	"editor.linkedEditing": true,
	"editor.suggestSelection": "first",
	"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
	"python.defaultInterpreterPath": "/opt/homebrew/bin/python3",
	"git.allowForcePush": true,
	"python.formatting.provider": "black",
	"[javascriptreact]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[dockercompose]": {
		"editor.defaultFormatter": "ms-azuretools.vscode-docker"
	},
	"files.exclude": {
		"**/.classpath": true,
		"**/.project": true,
		"**/.settings": true,
		"**/.factorypath": true
	},
	"[markdown]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"diffEditor.ignoreTrimWhitespace": false,
	"python.analysis.typeCheckingMode": "basic",
	"prettier.useTabs": true,
	"git.confirmSync": false,
	"emmet.excludeLanguages": ["markdown", "javascriptreact", "typescriptreact"],
	"breadcrumbs.enabled": false,
	"editor.minimap.enabled": false,
	"eslint.codeActionsOnSave.rules": null,
	"deno.inlayHints.parameterNames.enabled": "none",
	"deno.inlayHints.parameterTypes.enabled": false,
	"deno.inlayHints.enumMemberValues.enabled": false,
	"deno.inlayHints.functionLikeReturnTypes.enabled": false,
	"deno.inlayHints.variableTypes.enabled": false,
	"terminal.integrated.env.osx": {},
	"editor.wordWrap": "on",
	"editor.formatOnSave": true,
	"editor.tabSize": 2,
	"settingsSync.ignoredSettings": []
}

```

</p>
</details>

**Comment by fturmel** [comment] 2023-04-19 13:19
> @glekner and @fturmel, have either of you tried disabling the ESLint extension to see if that makes a difference?

I have not, but if I encounter the problem again today I will try to disable the ESLint and Prettier plugins and report back.

**Comment by marthoff** [comment] 2023-04-19 18:49
<img width="973" alt="image" src="https://user-images.githubusercontent.com/1391328/233171496-f5ea5f80-e5d8-4d31-872c-5d404f5f4fd7.png">

This is the screenshot. The error occurs randomly. I think it might be connected if the css or javascript is not correct. I experience it often, when my code is not complete, but I like to save in between.

**Comment by marthoff** [comment] 2023-04-19 20:37
Another guess: I think the problem occurs when I have the tailwind prettier plugin and intelli sense running.

**Comment by bengry** [comment] 2023-04-19 20:40
> Another guess: I think the problem occurs when I have the tailwind prettier plugin and intelli sense running.

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/755#issuecomment-1502218445

Maybe, but it's not the only cause, if it is indeed related. But maybe there's a common dominator with the eslint extension, since I am using that.

**Comment by marthoff** [comment] 2023-04-20 09:33
I turned off the tailwind prettier plugin (removed .prettierrc and npm remove plugin) and no more problems since then.

**Comment by joneath** [comment] 2023-04-20 22:07
☝️ removing the tailwind prettier plugin from `package.json` fixed the issue for me too.

**Comment by bengry** [comment] 2023-05-01 16:28
As @glekner mentioned, we don't use https://github.com/tailwindlabs/prettier-plugin-tailwindcss, but we do use https://github.com/francoismassart/eslint-plugin-tailwindcss, and have the `classnames-order` rule enabled, which apparently uses something related to prettier [under the hood](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/ea167fd9cb56b7fd1430b93e960736546bf71bd2/lib/rules/classnames-order.js#L178). Although it does implement [everything itself](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/lib/util/prettier/order.js) due to the naming I suspect it might've copied a bunch of code from the prettier plugin for tailwind for that, so that code might be the underlying issue here.

**Comment by bradlc** [comment] 2023-05-02 09:10
@bengry, if you disable/remove `eslint-plugin-tailwindcss` does the issue go away?

**Comment by bengry** [comment] 2023-05-16 15:24
> @bengry, if you disable/remove `eslint-plugin-tailwindcss` does the issue go away?

Sorry for the delayed response, had a bunch of things come up and I haven't had the time to check this.
Anyway, I just commented out anything tailwind-related in my ESLint config and it still seems to hang up VS Code very often after updating to the latest version of the extension.

**Comment by WoodyWoodsta** [comment] 2023-05-26 16:19
I've been butting my head against this. Even without this extension installed, saving would hang, specifically being stuck on the prettier formatting phase.

For me, removing the prettier-plugin-tailwind resolved the issue. I'm not sure why that is the case though - perhaps a race condition of some sort?

**Comment by hasokeric** [comment] 2023-06-04 20:07
Everytime mine hangs I see this in the Extension host, perhaps unrelated.

```
2023-06-04 16:02:30.957 [error] [bradlc.vscode-tailwindcss] provider FAILED
2023-06-04 16:02:30.980 [error] TypeError: Cannot read properties of null (reading 'filter')
    at Object.<anonymous> (c:\Users\Haso\.vscode-insiders\extensions\bradlc.vscode-tailwindcss-0.9.10\dist\extension.js:43:11904)
    at Generator.next (<anonymous>)
    at s (c:\Users\Haso\.vscode-insiders\extensions\bradlc.vscode-tailwindcss-0.9.10\dist\extension.js:1:1247)
```

**Comment by stormynight9** [comment] 2023-06-08 10:23
Any updates on how to fix this?

**Comment by xitanggg** [comment] 2023-06-12 05:14
I had this issue with `prettier-plugin-tailwindcss` version `0.3`, downgrading it back to say `0.2.1` with `npm install --save-dev prettier-plugin-tailwindcss@0.2.1`  and restarting VSCode solve the issue for me

**Comment by thecrypticace** [comment] 2023-06-15 15:41
I'm not 100% certain but it is possible this is related to https://github.com/microsoft/vscode/issues/184926

The fix for this has been merged in but I don't expect it'll be available until the next minor release of VSCode.

**Comment by hasokeric** [comment] 2023-06-15 17:06
I sure hope thats it.

**Comment by sumeetadur** [comment] 2023-06-16 13:26
> I'm not 100% certain but it is possible this is related to [microsoft/vscode#184926](https://github.com/microsoft/vscode/issues/184926)
> 
> The fix for this has been merged in but I don't expect it'll be available until the next minor release of VSCode.

https://github.com/microsoft/vscode/issues/184926#issuecomment-1594190928:
> This ships with `1.80.0-insiders`. Anyone is invited to give this a try and report back if the fix does what we want it to do ;-)

I've tried the Insiders build (https://code.visualstudio.com/insiders/) and it's working as expected 👍

**Comment by forbesd7** [comment] 2023-07-12 00:33
> > I'm not 100% certain but it is possible this is related to [microsoft/vscode#184926](https://github.com/microsoft/vscode/issues/184926)
> > The fix for this has been merged in but I don't expect it'll be available until the next minor release of VSCode.
> 
> [microsoft/vscode#184926 (comment)](https://github.com/microsoft/vscode/issues/184926#issuecomment-1594190928):
> 
> > This ships with `1.80.0-insiders`. Anyone is invited to give this a try and report back if the fix does what we want it to do ;-)
> 
> I've tried the Insiders build (https://code.visualstudio.com/insiders/) and it's working as expected 👍

+1 on this, seems to be working smoothly with this release!

**Comment by thecrypticace** [comment] 2023-07-12 03:07
Oh this is fantastic news! 🎉 🎉

If anyone here can give VSCode 1.80 a try (it's been out for several days now) and report back. I expect the issues are likely gone as some have experienced.

**Comment by davea38** [comment] 2023-07-12 10:27
I had this problem pre-1.80 and I have done two things to fix this:

1. Added a .prettierignore file in the root of my project
```json
build
coverage
.gitlab
.vscode
node_modules
```
2. Updated VSCode to 1.80

Still is slightly slow every now and again but it's a massive improvement!

**Comment by Suniron** [comment] 2023-07-18 06:58
Same behavior here:

![image](https://github.com/microsoft/vscode-edge-devtools/assets/36677774/0a0d19d5-c2cb-415d-bb28-28bddc945d0e)

How can I disable it? Because it takes a long time (almost 10s) to save my files with that.

This is my `.vscode/settings.json` configuration:

```
  "prettier.enable": false,
  "editor.formatOnSave": false,
  "[typescript]": {
    "editor.codeActionsOnSave": {
      "source.fixAll": false,
      "source.fixAll.eslint": true,
    },
  },
```

Windows 10 + WSL2 (Ubuntu).

In a monorepo turborepo/nuxt/vue/typescript

**Comment by glekner** [comment] 2023-07-18 09:54
Made a change couple of days ago and it seems like the issue is gone.
Try to go to the Output of the extension and see if it tries to parse a very large file, for me it was `yarn.lock`.

Since adding it to the Files exclude property i'm not experiencing the issue anymore
<img width="771" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/24938324/b530da73-0793-4f5c-ac6b-73530e433347">


@bradlc can you share your thoughts here? and why does the extension even parse these files?

**Comment by bradlc** [comment] 2023-07-18 10:09
Hey @glekner. The extension does not parse `yarn.lock` files. It watches it for changes only.

Are you certain that the improvement you're seeing is because of the configuration change, or could it be because you have upgraded VS Code to `v1.80` as @thecrypticace mentioned?

**Comment by glekner** [comment] 2023-07-18 11:27
@bradlc I have this configuration
```
    "tailwindCSS.validate": false,
    "tailwindCSS.lint.recommendedVariantOrder": "ignore",
    "tailwindCSS.codeActions": false,
    "tailwindCSS.files.exclude": [
      "**/.git/**",
      "**/node_modules/**",
      "**/.hg/**",
      "**/.svn/**",
      "**/yarn.lock",
      "**/@generated/**"
    ]
```
could it be related to code actions?

**Comment by davea38** [comment] 2023-07-19 08:52
@bradlc Is there a way to point this plugin at an exclusion file (such as .prettierignore or .eslintignore)? There's lots of discussion on the prettier / eslint github issues on centralising exclusions. The typical way is to point the addons via the package.json at an exclude file in the .gitignore format

**Comment by TruJared** [comment] 2023-07-22 10:41
I had this same issue today using VSCode v. 1.80.1. Creating a`.prettierignore` file and adding the larger directories to it ([referenced by davea38](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/755#issuecomment-1632250315)) seemed to resolve the issue. 

_.prettierignore_
```
.next
.vscode
node_modules
```

**Comment by glekner** [comment] 2023-08-17 08:35
Issue is gone @bradlc , but i'm not sure its related to VSCode version.
this is my config

```
    "tailwindCSS.validate": false,
    "tailwindCSS.lint.recommendedVariantOrder": "ignore",
    "tailwindCSS.codeActions": false,
    "tailwindCSS.files.exclude": [
      "**/.git/**",
      "**/node_modules/**",
      "**/.hg/**",
      "**/.svn/**",
      "**/yarn.lock",
      "**/@generated/**"
    ]
```

could it be related to code actions?

**Comment by bradlc** [comment] 2023-08-17 09:12
@glekner If you set `tailwindCSS.codeActions` to `true` does the issue come back?

**Comment by localpath** [comment] 2023-09-27 00:01
Still causes major issues for me both in monorepos running nextjs13, nextjs12, nestjs and some using containers for local dev others no containers.

Seems like for me the `"tailwindCSS.validate": false` fixes the issue. Nextjs 13 would take around 30sec to compile and with the setting to false takes around 9s for first compile, around 8s with the plugin completely disabled. (inside container on mounted shared volumes using turborepo).

**Comment by thecrypticace** [comment] 2023-11-02 17:58
@localpath do you mean it would take around 30s for it to provide completions? The intellisense extension does not run as part of the nextjs build process (I guess unless you're running the language server yourself during the build).

**Comment by thecrypticace** [comment] 2023-11-10 15:40
I've done some perf testing of diagnostics and don't seem to be able to reproduce perf issues here in the latest version of VSCode.

Because this issue has had very little activity in the last couple of months and not enough info available to reliably reproduce — I'm going to go ahead and close it.

If this issue pops up again, please leave a comment with details on your VSCode setup (version, config, all installed extensions), a repository that can be cloned to reproduce this issue, and information about how you're using Intellisense (for instance — is it in a Remote workspace over SSH) and I will take a look again.

**Closed by thecrypticace** 2023-11-10 15:40 UTC

**Comment by TheGreatDaniad** [comment] 2024-01-06 17:53
I have literally done all of the suggested solutions. Non worked for me!

**Comment by localpath** [comment] 2024-01-07 00:18
@thecrypticace sorry for the late response. It would cause the Nextjs dev server to hang or become unfunctional after a few minutes. I think it was just some weird interaction with WSL 2, Docker shared volumes, HMR, and VSCode sort of bottlenecking or causing things trying to access the filesystem to hang.

Doesn't seem to happen anymore so not sure if Nextjs or VSCode did something that fixed it.

**Comment by niczyporukm** [comment] 2024-03-27 15:26
Mentioned behaviors may be caused by other VS Code plugins that analyze files onSave. Disabling the "Auto Import - ES6, TS, JSX, TSX" plugin solved the issue in my case.

**Comment by kimsuyeon0916** [comment] 2024-08-08 18:05
Remove the `yarn.lock` file and then run the `yarn install` command. 
The problem may be caused by a damaged `yarn.lock` file and less installed dependencies. I solved this problem like this.

```shell
rm yarn.lock
yarn install
```

**Comment by channprj** [comment] 2024-09-26 02:01
@glekner You saved my time a lot.

Also, I removed auto import extension, too. Check your `Output` in vscode. You can see reasons for taking it slow.

**Comment by ekrata-main** [comment] 2025-04-12 08:57
```json
{
"tailwindCSS.validate": false
}
```
