### ISSUE TITLE
after use this svg, ti is disabled

### ISSUE THREAD

**Issue by Zerounary** [tailwindlabs/tailwindcss-intellisense#417] opened 2021-09-24 06:53 UTC
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" t="1632212715826" class="icon" viewBox="0 0 1024 1024" version="1.1" p-id="2549" width="32" height="32"><defs><style type="text/css"/></defs><path d="M801.152 608c14.336 0 28.64 12.352 30.624 28.288L832 640v96c0 33.728-28.096 61.376-60.832 63.84l-4.704 0.16H253.696c-33.12 0-59.2-26.144-61.536-59.2L192 736v-96c0-17.696 15.424-32 30.848-32 17.92 0 29.12 12.352 30.656 28.288l0.192 3.712v96h512.768v-96c0-17.696 15.424-32 34.688-32zM512 224c14.336 0 28.64 12.352 30.624 28.256l0.224 3.744v313.472l77.12-65.536c11.52-11.648 30.816-10.304 42.4 3.008 10.656 12.256 11.52 30.4 2.464 42.304l-2.464 2.816-131.104 112c-10.56 9.696-24.416 10.496-38.528 2.432l-3.84-2.432-127.264-112c-11.552-11.648-15.424-31.84-3.84-45.12 10.656-12.288 31.2-14.4 43.392-5.472l80 68V256c0-17.664 11.52-32 30.816-32z" fill="#2c2c2c" p-id="2550"/></svg>
`

Visual Studio Code version: 1.60.2.
Tailwindcss-intellisense version is v0.6.14.

**Comment by bradlc** [comment] 2021-09-24 09:37
Duplicate of #402

**Closed by bradlc** 2021-09-24 09:37 UTC
