### ISSUE TITLE
IntelliSense no longer come once Just-in-Time Mode is enabled.

### ISSUE THREAD

**Issue by mforstme** [tailwindlabs/tailwindcss-intellisense#297] opened 2021-04-07 18:27 UTC
IntelliSense no longer come once Just-in-Time Mode is enabled.

Comment out `mode: 'jit'` in the tailwind.config.js, it works again. 

Visual Studio Code v1.55.0
node v15.14.0
npm v7.8.0
tailwindcss v2.1.1
Tailwind CSS IntelliSense v0.5.9

The output of the tailwindcss-intellisense extension:

Found Tailwind config file: /path/to/project/tailwind.config.js
Found tailwindcss v2.1.1: /path/to/project/node_modules/tailwindcss

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
Failed to initialise: TypeError: Cannot read property 'map' of undefined
    at /path/to/project/node_modules/tailwindcss/jit/lib/setupContext.js:783:9
    at /path/to/project/node_modules/tailwindcss/jit/index.js:35:47
    at LazyResult.runOnRoot (/path/to/project/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/path/to/project/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/path/to/project/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/path/to/project/node_modules/postcss/lib/lazy-result.js:190:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by PaulPCIO** [comment] 2021-04-07 21:46
Yea got the same problem,

![image](https://user-images.githubusercontent.com/39598117/113938787-5c890080-97fb-11eb-973c-80581cbcaad3.png)
![image](https://user-images.githubusercontent.com/39598117/113938802-614db480-97fb-11eb-8e7e-eef249c42937.png)

**Comment by bradlc** [comment] 2021-04-07 22:41
Duplicate of #293

**Closed by bradlc** 2021-04-07 22:41 UTC
