### ISSUE TITLE
Variants with two colons are [partially?] ignored

### ISSUE THREAD

**Issue by timfee** [tailwindlabs/tailwindcss-intellisense#202] opened 2020-10-12 01:15 UTC
The default regular expression picks up the entire className value correctly, but:

* `dark:bg-white` works, as expected.
* `dark:hover:bg-black` does not work. 

What's strange is that the plugin *will* auto suggest `dark:hover` and after the second `:` it doesn’t return anything. See my [tailwind.config.js](https://github.com/timfee/homepage/blob/master/tailwind.config.js) here.

1: 
<img width="593" alt="Screen Shot 2020-10-11 at 6 05 58 PM" src="https://user-images.githubusercontent.com/3246342/95695842-9df27780-0bed-11eb-9185-f8944c0b0773.png">

2:
<img width="625" alt="Screen Shot 2020-10-11 at 6 06 04 PM" src="https://user-images.githubusercontent.com/3246342/95695852-a5198580-0bed-11eb-9f47-49905861d450.png">

3:
<img width="509" alt="Screen Shot 2020-10-11 at 5 59 33 PM" src="https://user-images.githubusercontent.com/3246342/95695858-aa76d000-0bed-11eb-828b-9ab4b08e19a7.png">

**Comment by timfee** [comment] 2020-10-12 01:16
Also: I wonder if, actually, this has to do with multiple variants being applied at the same time. I'm using the `!` prefix to designate that `!important` should be added -- and `!m-0` works, but `!dark:m-0` does’t.

**Comment by deadcoder0904** [comment] 2020-10-24 11:22
@timfee unrelated, what's the theme?

**Comment by bradlc** [comment] 2020-11-19 12:50
Looks like this might have been related to an issue with `dark:` classes specifically, which has now been fixed in `v0.5.0` of the extension. Can you confirm that the issue is resolved @timfee?

**Comment by bradlc** [comment] 2021-01-08 16:33
Going to close this as I think it should be resolved now, but please open a new issue if not 👍

**Closed by bradlc** 2021-01-08 16:33 UTC
Labels: bug, question
