### ISSUE TITLE
Intellinsense not working when using tailwind-cli via django-tailwind-cli package

### ISSUE THREAD

**Issue by applewebbo** [tailwindlabs/tailwindcss-intellisense#924] opened 2024-03-15 13:43 UTC
**What version of VS Code are you using?**

Version: 1.87.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.10.5

**What version of Tailwind CSS are you using?**

Tailwind CLI version to 3.4.1

**What package manager are you using?**

Tailwind CLI via [django-tailwind-cli](https://github.com/oliverandrich/django-tailwind-cli)

**What operating system are you using?**

Mac Os Sonoma 14.4

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");
const { spawnSync } = require("child_process");

// Calls Django to fetch template files
const getTemplateFiles = () => {
  const command = "python3";
  const args = ["manage.py", "tailwind", "list_templates"];
  // Assumes tailwind.config.js is located in the BASE_DIR of your Django project.
  const options = { cwd: __dirname };

  const result = spawnSync(command, args, options);

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    console.log(result.stdout.toString(), result.stderr.toString());
    throw new Error(
      `Django management command exited with code ${result.status}`
    );
  }

  const templateFiles = result.stdout
    .toString()
    .split("\n")
    .map((file) => file.trim())
    .filter(function (e) {
      return e;
    }); // Remove empty strings, including last empty line.
  return templateFiles;
};

module.exports = {
  content: [].concat(getTemplateFiles()),
  theme: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/container-queries"),
    plugin(function ({ addVariant }) {
      addVariant("htmx-settling", ["&.htmx-settling", ".htmx-settling &"]);
      addVariant("htmx-request", ["&.htmx-request", ".htmx-request &"]);
      addVariant("htmx-swapping", ["&.htmx-swapping", ".htmx-swapping &"]);
      addVariant("htmx-added", ["&.htmx-added", ".htmx-added &"]);
    }),
  ],
};

```

**VS Code settings**

```json
    "tailwindCSS.emmetCompletions": true,
    "editor.inlineSuggest.enabled": true,
    "editor.quickSuggestions": {
        "strings": true
    },
    "css.validate": false,
```

**Reproduction URL**

Cannot reproduce my bug on GitHub as is simply not activating correctly on django template files

**Describe your issue**

Intellisense is not activating on the html files, I cannot see suggestions or linting. I have a tailwind.cofig.js in the root folder of my project and tailwind installed via tailwind-cli. I can see intellisense working normally when installing tailwinds via npm or via tailwind-cli using another package [pytailwindcss](https://github.com/timonweb/pytailwindcss)

**Comment by thecrypticace** [comment] 2024-03-25 20:33
I just set up a fresh VM with a small Django project and didn't have any issues with Intellisense. It's likely that loading your tailwind config is somehow erroring. I'll say that `django-tailwind-cli` using stdout as the list of files is strange to me because the output includes more than just files paths: 
<img width="970" alt="Screenshot 2024-03-25 at 16 26 12 1" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/614993/2a788548-2ddc-45cd-915c-62b89a3215aa">

… and this could be related to _why_ it's erroring. Can you try this:
- Update to the extension pre-release (just for this test) if you've not already
- Open your project
- Run "Tailwind CSS: Show Output" in the VSCode command palette
- Re-save your config file and see if any errors are logged

If you do that, are still having problems, but don't see any errors can you attach a clonable reproduction of the project you're working with (a fresh project is fine as long as it reproduces the issue you are seeing).

**Comment by thecrypticace** [comment] 2024-04-11 17:17
Gonna close this as I've not heard anything back. If you can provide the above info I'll gladly take a look and see if I can figure out what's going on here. Thanks!

**Closed by thecrypticace** 2024-04-11 17:17 UTC
Labels: question

**Comment by applewebbo** [comment] 2024-04-11 17:59
Sorry for not having seen your first response. I totally agree that is something related to the autogenerated tailwind config of the django-tailwind-cli. I've switched to a more common configuration and the intellisense works like a charm.. thanks for your time investigating it
