### ISSUE TITLE
Jit Mode Per-side border colors auto complete suggestion not showing

### ISSUE THREAD

**Issue by mehdad-hussain** [tailwindlabs/tailwindcss-intellisense#419] opened 2021-09-26 09:36 UTC
Hello,
I am using this extension. It's nice extension for tailwind CSS.
But for JIT mode border-t-red-900 or border-b-blue-900
these suggestion is not showing.
[https://tailwindcss.com/docs/just-in-time-mode#per-side-border-colors](url)
Like here mentioned in the official docs.

**Comment by bradlc** [comment] 2021-09-27 09:20
Duplicate of #375

**Closed by bradlc** 2021-09-27 09:20 UTC
