### ISSUE TITLE
Should this extension be suggesting my custom classes?

### ISSUE THREAD

**Issue by redders6600** [tailwindlabs/tailwindcss-intellisense#250] opened 2021-01-22 06:05 UTC
I'm not sure whether something in my project is set up wrong, or whether the scope of this extension ends with the built in tailwind classes?

Either way it would be great to be able to define a class in CSS using `@apply` etc and have it show up in the suggestions.

**Comment by bradlc** [comment] 2021-01-22 10:49
Hey @redders6600. No, the extension only suggests classes generated by Tailwind, including any plugins. This is something that I would like to support one day, perhaps with a new VS Code setting so you can specify your CSS "entry" file. I'm going to close this as a duplicate of #227, thanks!

**Closed by bradlc** 2021-01-22 10:49 UTC
