### ISSUE TITLE
ESM tailwind config is not supported

### ISSUE THREAD

**Issue by babyface001** [tailwindlabs/tailwindcss-intellisense#654] opened 2022-11-05 01:52 UTC
**What version of Tailwind CSS IntelliSense are you using?**

Marketplace version

**What version of Tailwind CSS are you using?**
3.0

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {"50":"#f5f3ff","100":"#ede9fe","200":"#ddd6fe","300":"#c4b5fd","400":"#a78bfa","500":"#8b5cf6","600":"#7c3aed","700":"#6d28d9","800":"#5b21b6","900":"#4c1d95"}
      }
    },
  },
  plugins: [],
}

```

**Describe your issue**

 Tailwind CSS: require() of ES Module tailwind.config.js from .vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js not supported.

**Comment by bradlc** [comment] 2022-11-07 12:03
Duplicate of #565 #592

**Closed by bradlc** 2022-11-07 12:03 UTC
