### ISSUE TITLE
CLI version ?

### ISSUE THREAD

**Issue by nvuillam** [tailwindlabs/tailwindcss-intellisense#368] opened 2021-07-15 21:28 UTC
Is it possible to call the linter/formatter of your extension via command line ?

That would be great for CI, some people still don't use VsCode ^^ (note: I'm not part of them 👼  )

Thanks !

**Comment by bradlc** [comment] 2021-08-13 12:51
Duplicate of #346

**Closed by bradlc** 2021-08-13 12:51 UTC
