### ISSUE TITLE
Wrong cssConflict warning

### ISSUE THREAD

**Issue by benjaminpayoux** [tailwindlabs/tailwindcss-intellisense#136] opened 2020-06-25 13:15 UTC
Hello 👋🏼,
Thanks for this great plugin!

I encountered this case where the plugin display a warning regarding a cssConflict lint, which I think should not be here :) 

<img width="369" alt="Capture d’écran 2020-06-25 à 15 11 13" src="https://user-images.githubusercontent.com/1423027/85726189-26f4aa00-b6f6-11ea-9395-9fd54cb1f1ab.png">

Nothing serious, though ;)

**Comment by bradlc** [comment] 2020-06-25 15:18
Hey @benjaminpayoux. Really weird, what happens if you close that file and reopen it?

**Comment by benjaminpayoux** [comment] 2020-06-26 07:18
Close / reopen the file or vscode produces the same issue.

**Comment by benjaminpayoux** [comment] 2020-06-29 08:01
Here are the extensions install in my vscode :
<img width="316" alt="Capture d’écran 2020-06-29 à 09 59 22" src="https://user-images.githubusercontent.com/1423027/85988515-6a4d6200-b9ef-11ea-95a9-ffbad6fd27f9.png">

I don't know if it could be in conflict with one of them.
I will try on a fresh install too.

**Comment by bradlc** [comment] 2020-06-29 11:55
🤔 Would you be able to share the whole file that this is happening in?

**Comment by benjaminpayoux** [comment] 2020-06-29 13:40
Sure :) the weird thing is that there is the same classes at line 23 but the plugin does not throw the warning 🧐

Here is the file :

```html
<template>
    <div
        class="absolute z-50 w-full h-full inset-0 bg-white flex flex-col overflow-hidden rounded-lg px-4 py-3"
        style="box-shadow: 0px 4px 20px 0px rgba(0,0,0,0.2);
        "
    >
        <div>
            <h3 class="text-center font-semibold">Accompagnateurs</h3>
            <div @click="showGroupForm = false" class="absolute top-0 right-0 m-4 cursor-pointer">
                <ic-close
                    @click="$emit('close-additional-guests-modal')"
                    class="w-3 h-3 fill-current text-gray-dark hover:text-gray-light"
                />
            </div>
        </div>

        <div class="mt-2">
            <ul class="flex flex-row flex-shrink-0 flex-no-wrap w-full text-sm xl:text-base">
                <li
                    v-if="event.user_can_add_additional_guest_adults"
                    :class="{
                        'border-b-2 border-green': additionalGuestsFilter === additionalGuestsFilters.ADULT && event.user_can_add_additional_guest_children,
                        'border-b border-black border-opacity-10': additionalGuestsFilter !== additionalGuestsFilters.ADULT,
                    }"
                    class="flex flex-1 flex-shrink-0 cursor-pointer justify-center"
                    @click="filterGuests(additionalGuestsFilters.ADULT)"
                >
                    <span
                        :class="{
                            'border-b-2 border-green': 
                                event.user_can_add_additional_guest_adults 
                                && !event.user_can_add_additional_guest_children
                        }"
                        class="px-4 py-1"
                    >Adulte(s)</span>
                </li>
                <li
                    v-if="event.user_can_add_additional_guest_children"
                    :class="{
                        'border-b-2 border-green': additionalGuestsFilter === additionalGuestsFilters.CHILD && event.user_can_add_additional_guest_adults,
                        'border-b border-black border-opacity-10': additionalGuestsFilter !== additionalGuestsFilters.CHILD,
                    }"
                    class="flex flex-1 flex-shrink-0 cursor-pointer justify-center"
                    @click="filterGuests(additionalGuestsFilters.CHILD)"
                >
                    <span
                        :class="{
                            'border-b-2 border-green': 
                                !event.user_can_add_additional_guest_adults 
                                && event.user_can_add_additional_guest_children
                        }"
                        class="px-4 py-1"
                    >Enfant(s)</span>
                </li>
            </ul>
        </div>
        <div class="relative flex-1 overflow-y-auto" ref="snackbarContainer">
            <div class="h-full">
                <div
                    class="flex items-center cursor-pointer py-3 border-b border-black border-opacity-10"
                    @click="addAdditionalGuest"
                >
                    <ic-add-big-plus
                        class="w-10 xl:w-12 h-10 xl:h-12 mr-3 fill-current text-gray-light"
                    ></ic-add-big-plus>
                    <span class="text-sm">{{buttonText}}</span>
                </div>
                <div id="additional-guest-list" class="flex flex-row w-full">
                    <div class="flex-col w-full">
                        <!-- ADULTS -->
                        <div v-if="additionalGuestsFilter === additionalGuestsFilters.ADULT">
                            <div
                                v-for="(additionalGuest, index) in additionalGuestsAdultList"
                                :key="index"
                                class="py-2 flex flex-row items-center w-full"
                            >
                                <div
                                    class="flex items-center justify-center relative w-10 xl:w-12 h-10 xl:h-12 rounded-full bg-gray-light border-2 border-white"
                                >
                                    <img
                                        class="absolute w-full h-full object-cover rounded-full"
                                        v-if="additionalGuest.avatar"
                                        v-auth-image="guest.avatar + '&width=48'"
                                    />
                                    <span>{{ additionalGuest.acronym() }}</span>
                                </div>
                                <div class="flex flex-row flex-grow items-center ml-3">
                                    <div class="flex-grow text-sm">{{additionalGuest.name}}</div>

                                    <ic-dots-vertical
                                        class="cursor-pointer w-4 h-4 fill-current text-gray-light"
                                    />
                                </div>
                            </div>
                        </div>
                        <!-- CHILDREN -->
                        <div v-if="additionalGuestsFilter === additionalGuestsFilters.CHILD">
                            <div
                                v-for="(additionalGuest, index) in additionalGuestsChildList"
                                :key="index"
                            >
                                <div class="pt-3 flex items-center w-full">
                                    <div class="flex flex-col w-1/2">
                                        <label class="text-2xs text-gray-light">PRÉNOM</label>
                                        <input class="text-sm mr-2" v-model="additionalGuest.name" />
                                    </div>
                                    <div class="w-1/2 flex flex-row justify-between items-center">
                                        <div class="flex flex-col w-2/3">
                                            <span class="text-2xs text-gray-light">ÂGE</span>
                                            <span class="text-sm">3 ans</span>
                                        </div>
                                        <ic-trash
                                            @click="deleteAdditionalGuest(index)"
                                            class="w-4 h-4 fill-current text-gray-light mr-4 cursor-pointer"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="btn w-full max-w-md mt-2" @click="saveAdditionalGuests">Valider</button>
        <LoadingComponent v-if="isLoading" class="bg-black bg-opacity-70" />
    </div>
</template>

<script lang="ts" src="./AdditionalGuestsComponent.ts" />

```

**Comment by bradlc** [comment] 2020-06-29 14:29
Brilliant, thanks @benjaminpayoux! I can reproduce the issue so I'll take a proper look at it this afternoon

**Comment by jsbrain** [comment] 2020-07-03 15:10
Faced the same "issue":

<img width="564" alt="Screenshot 2020-07-03 17 07 34" src="https://user-images.githubusercontent.com/20225909/86481243-ed541c80-bd4f-11ea-844c-a0c4fb7abe0a.png">

simple reordering fixes it:

<img width="544" alt="Screenshot 2020-07-03 17 07 59" src="https://user-images.githubusercontent.com/20225909/86481259-f513c100-bd4f-11ea-82ea-b1848ebeb642.png">

Happy debugging 😁

**Comment by bradlc** [comment] 2020-08-25 16:03
This was fixed in `v0.4.2` 👍

**Closed by bradlc** 2020-08-25 16:03 UTC
Labels: bug

**Comment by OnkelTem** [comment] 2022-08-31 14:45
It doesn't look to be fixed or it's a similar issue.

```tsx
return (
    <table tw="table-auto w-full">
      <tbody>
        {rows.map((row, index) => (
          <tr key={index}>
            <th tw="text-left py-1 pl-2 font-normal border border-gray-200">{row[0]}</th>
            {row[1].map((item, index) => (
              <td
                tw="text-right py-1 pl-2 pr-1 border border-gray-200 font-bold"
                key={index}
              >
                {item}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  )
```

![image](https://user-images.githubusercontent.com/114060/187707652-caea8a04-9548-44ce-9e26-bcee1d985469.png)

**Comment by wiredearp** [comment] 2022-10-20 04:15
I'm also getting this big time with my highly customized preset, for example with the following two declarations that are quite obviously not related except they are both `@layer components`.

```css
.body-02 {
 font-weight: 400;
 font-size: clamp(0.875rem, 0.163265306122449vw + 0.8367346938775511rem, 1rem);
 line-height: 1.5;
}
```

and (compiled into the same file before presented to Tailwind)

```css
.theme-dark {
  --color-action-secondary-default: var(--color-core-blue-500);
  --color-action-secondary-hovered: var(--color-core-blue-400);
  --color-action-secondary-pressed: var(--color-core-blue-600);
  /* only variables in this selector */
}
```

I will return with a simplified test case since I find this conflict detection to be quite the selling point, for now I just wanted to keep this issue alive.

**Comment by OnkelTem** [comment] 2022-12-13 16:24
So how to get rid of this annoying thing? How to disable it completely?

**Comment by katekostina** [comment] 2023-06-14 09:40
I've also encountered this, it happens almost in every file, had to disable all the cssConflict warnings.
<img width="951" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/60067138/cce0a104-ea94-44fa-8744-3c9b91b0e698">

**Comment by katekostina** [comment] 2023-06-14 09:42
> So how to get rid of this annoying thing? How to disable it completely?

I've turned it off like this in VSC: in the top menu Code -> Preferences -> Settings
<img width="1105" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/60067138/269ec9d7-7eed-46c1-b99b-aac83d9d42ab">

**Comment by jpcmf** [comment] 2023-06-27 21:21
@katekostina Nice tip. It was annoying me (=

**Comment by zce** [comment] 2023-11-06 05:54
Similar issues have occurred in the latest v0.10.3 version

![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/6166576/44c2aad3-028f-40dd-a00f-2d1f0ce8a00b)

**Comment by zce** [comment] 2023-11-06 12:27
> Similar issues have occurred in the latest v0.10.3 version
> 
> ![image](https://user-images.githubusercontent.com/6166576/280607076-44c2aad3-028f-40dd-a00f-2d1f0ce8a00b.png)

I know what the reason is, it's because I configured an inappropriate `tailwindCSS.experimental.classRegex`
