### ISSUE TITLE
tailwindcss-intellisense is not working

### ISSUE THREAD

**Issue by thiras** [tailwindlabs/tailwindcss-intellisense#209] opened 2020-11-06 07:53 UTC
Hello,
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic
```

I have a tailwind.config.js file on my project root.
![Screenshot from 2020-11-06 10-49-11](https://user-images.githubusercontent.com/5150432/98340025-c0758600-201d-11eb-9e3c-c3dc331dda89.png)

```js
// tailwind.config.js
module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: ['./components/**/*.{js,ts,jsx,tsx}', './pages/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'accent-1': '#333',
      },
    },
  },
  variants: {},
  plugins: [],
}
```

Not a single line of log on Output -> tailwindcss-intellisense.

The intellisense is not working even after complete OS reboot.

![Screenshot from 2020-11-06 10-52-29](https://user-images.githubusercontent.com/5150432/98340303-3843b080-201e-11eb-9d8b-84ea7b3fa5a1.png)

**Comment by thiras** [comment] 2020-11-06 15:53
I've just updated my Code. Also reset all the code config folders. The problem still presist.

```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic
```

**Comment by thiras** [comment] 2020-11-06 16:34
My tailwindcss-intellisense output log is empty but here is my Log (Extension Host) output;

```
[2020-11-06 19:32:38.538] [exthost] [info] extension host started
[2020-11-06 19:32:38.654] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2020-11-06 19:32:38.654] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-11-06 19:32:38.667] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:javascript"}
[2020-11-06 19:32:38.667] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/typescript-language-features/dist/extension
[2020-11-06 19:32:38.675] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-11-06 19:32:38.675] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-11-06 19:32:38.677] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-11-06 19:32:38.677] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2020-11-06 19:32:38.687] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-11-06 19:32:38.687] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/git/dist/main
[2020-11-06 19:32:38.702] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-11-06 19:32:38.703] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-11-06 19:32:38.705] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-11-06 19:32:38.705] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/search-result/dist/extension.js
[2020-11-06 19:32:38.706] [exthost] [info] ExtensionService#_doActivateExtension deepcode.deepcode {"startup":true,"extensionId":{"value":"deepcode.deepcode","_lower":"deepcode.deepcode"},"activationEvent":"*"}
[2020-11-06 19:32:38.706] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/deepcode.deepcode-3.0.7/out/extension.js
[2020-11-06 19:32:38.813] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"*"}
[2020-11-06 19:32:38.813] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/eamodio.gitlens-10.2.3/dist/extension
[2020-11-06 19:32:38.831] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":true,"extensionId":{"value":"ms-vsliveshare.vsliveshare","_lower":"ms-vsliveshare.vsliveshare"},"activationEvent":"*"}
[2020-11-06 19:32:38.831] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.3121/out/prod/extension-prod
[2020-11-06 19:32:39.139] [exthost] [info] ExtensionService#_doActivateExtension TabNine.tabnine-vscode {"startup":true,"extensionId":{"value":"TabNine.tabnine-vscode","_lower":"tabnine.tabnine-vscode"},"activationEvent":"*"}
[2020-11-06 19:32:39.139] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/tabnine.tabnine-vscode-3.1.5/out/extension
[2020-11-06 19:32:39.171] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":true,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"workspaceContains:package.json"}
[2020-11-06 19:32:39.171] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/npm/dist/npmMain
[2020-11-06 19:32:39.271] [exthost] [info] ExtensionService#_doActivateExtension bradlc.vscode-tailwindcss {"startup":true,"extensionId":{"value":"bradlc.vscode-tailwindcss","_lower":"bradlc.vscode-tailwindcss"},"activationEvent":"workspaceContains:**/{tailwind,tailwind.config,tailwind-config,.tailwindrc}.js"}
[2020-11-06 19:32:39.271] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/extension/index.js
[2020-11-06 19:32:39.389] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2020-11-06 19:32:39.389] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2020-11-06 19:32:39.391] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-11-06 19:32:39.391] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2020-11-06 19:32:39.557] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2020-11-06 19:32:39.558] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2020-11-06 19:32:39.641] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":false,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-11-06 19:32:39.642] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/github/dist/extension.js
[2020-11-06 19:32:39.826] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2020-11-06 19:32:39.826] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2020-11-06 19:32:41.677] [exthost] [info] eager extensions activated
[2020-11-06 19:32:41.714] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":false,"extensionId":{"value":"dbaeumer.vscode-eslint","_lower":"dbaeumer.vscode-eslint"},"activationEvent":"onStartupFinished"}
[2020-11-06 19:32:41.714] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/dbaeumer.vscode-eslint-2.1.13/client/out/extension
[2020-11-06 19:32:41.721] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2020-11-06 19:32:41.721] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/thiras/.vscode/extensions/esbenp.prettier-vscode-5.7.1/dist/extension
```

**Comment by wadhah101** [comment] 2020-11-14 16:05
Having the same exact problem with nextjs and no logs
did you solve it ?

**Comment by thiras** [comment] 2020-11-14 16:49
@wadhah101 no it's still unsolved.

**Comment by wadhah101** [comment] 2020-11-14 19:40
No I using node 14 on linux

**Comment by wadhah101** [comment] 2020-11-15 09:54
update , tailwindcss is giving an output  , code repo [https://github.com/wadhah101/insat-schedule](url)
`(node:24620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classNames' of undefined
    at Object.t.getClassNameParts (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:31:37152)
    at Object.t.getClassNameDecls (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:45:620)
    at /home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:13:78172
    at Array.forEach (<anonymous>)
    at /home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:13:78148
    at Array.forEach (<anonymous>)
    at Object.t.getCssConflictDiagnostics (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:13:78096)
    at /home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:1:169311
    at Generator.next (<anonymous>)
    at s (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:1:168610)
(node:24620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classNames' of undefined
    at Object.t.getClassNameParts (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:31:37152)
    at Object.t.getClassNameDecls (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:45:620)
    at /home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:13:78172
    at Array.forEach (<anonymous>)
    at /home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:13:78148
    at Array.forEach (<anonymous>)
    at Object.t.getCssConflictDiagnostics (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:13:78096)
    at /home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:1:169311
    at Generator.next (<anonymous>)
    at s (/home/boogie/.vscode-oss/extensions/bradlc.vscode-tailwindcss-0.4.3/dist/server/index.js:1:168610)
(node:24620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`

**Comment by filipac** [comment] 2020-11-17 09:29
it stopped working for me too like a week ago, don't have any error logs that i can find.

**Comment by ZayRTun** [comment] 2020-11-17 17:14
On my current project, I did some changes in my webpack.mix.js file then I compiled it using "npm run dev" and after that, the IntelliSense stopped working. It works on other laravel projects. Plus, I tried removing the whole tailwind package and install it again but still, it's not working.

**Comment by themustafaomar** [comment] 2020-11-20 13:53
Pulling my hair out here, waiting for a solution :'(

**Comment by sanny-io** [comment] 2020-11-28 21:11
> Pulling my hair out here, waiting for a solution :'(
> EDIT:
> This solution worked for me (I don't know why 👀)
> https://stackoverflow.com/a/63549595

This _kind of_ worked for me. I see the classes, but can't preview the colors as shown below.

![](https://tailwindcss.com/_next/static/media/intellisense.0bd2cbf8c277e6c1330e345ab3cd7684.png)

**Comment by filipac** [comment] 2020-11-28 22:04
@sanny-io @bradlc what I discovered was that some extensions i had in a dependency had a tailwind.config.js here and that was caugth first by the plugin. 

@bradlc i am not very familiar with the workflow to run extesions locally to add new features, would it make sense to have a config value to specify the tailwind.config.js file instead of automatically picking the first from that array (https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-intellisense/src/class-names/index.js#L41-L53)

Maybe show a warning message if multiple files found in that array and tell the user to  manually specify the config file. In my case, the first found was not used and yarn install has not been made in that folder, once I deleted it the first file in the following array was the good one and intellisense started to work again.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/271155/100526944-70ca4a80-31d6-11eb-9e20-744eb9529e6b.png">

**Comment by themustafaomar** [comment] 2020-11-29 05:57
@sanny-io 
The exact same behavior here when working with Vue files, the colors don't show.

![image](https://user-images.githubusercontent.com/46113191/100534510-50bb7b00-3218-11eb-9cfd-e3111d6bda5a.png)

But the native HTML files working perfectly, I don't know why as well :'(

![image](https://user-images.githubusercontent.com/46113191/100534525-8496a080-3218-11eb-8bb3-45641514da2c.png)

**Comment by filipac** [comment] 2020-11-30 16:15
@themustafaomar maybe you also have multiple tailwind.config.js files?

**Comment by mattrossman** [comment] 2020-11-30 22:41
For me, intellisense is broken when using Create React App, but it works when I use Next.js

I followed the official instructions for each as listed here: https://tailwindcss.com/docs/installation

**Comment by themustafaomar** [comment] 2020-12-01 09:35
> @themustafaomar maybe you also have multiple tailwind.config.js files?

In my root directory, Nope!

But finally, I solved my issue, and it was because of using `import` statements in my `tailwind.config.js`
We should replace it with `require`, one single `import` or error can disable the extension entirely without knowing why!

Wrong way:
```js
// tailwind.config.js
import some from './file'

export default {}
```

Right way:
```js
// tailwind.config.js
const some = require('./file')

module.exports = {}
```

**Comment by drewbolles** [comment] 2020-12-01 19:08
I can confirm this has stopped working for my NextJS projects as well

**Comment by bradlc** [comment] 2020-12-02 14:40
@thiras can I ask what specifically isn't working? Your screenshot indicates that it is working fine, since you have color decorators next to some of your classes (`bg-blue-500 text-white`), which are provided by the extension.

**Comment by TaylorFacen** [comment] 2020-12-04 14:08
Following this thread because I just install Intellisense in VSCode but the extension doesn't appear to work (I'm using Create React App and followed the installation instructions on the website)

**Comment by ah-yu** [comment] 2020-12-08 02:18
the extension doesn't work in vscode-darwin-arm64 but work in vscode stable build

**Comment by yhatt** [comment] 2020-12-12 01:36
I've also met this in VS Code 1.53 exploration for Apple Silicon.

https://github.com/tailwindlabs/tailwindcss-intellisense/blob/84e3bf4b3a81c3fb659bd58e28b95c9252cc0ee1/packages/tailwindcss-intellisense/src/class-names/index.js#L35

And curiously I've found this `glob` is never resolved in ARM64 build. It's working well in VS Code for Intel Mac build running through Rosetta 2.

For some reason, just changing `glob` to `glob.sync` will work on ARM64 well. Would it be better to submit pull request?

```
Version: 1.53.0-exploration
Commit: d530b3b27d0f52a0290cdb53031ba60f02927c60
Date: 2020-12-10T07:00:45.477Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0
```

#### Related 

- https://github.com/tailwindlabs/tailwindcss-intellisense/issues/209#issuecomment-740316046
- https://github.com/microsoft/vscode/issues/106770#issuecomment-743311309
- https://github.com/microsoft/vscode/issues/112225

**Comment by yhatt** [comment] 2020-12-12 09:40
Following is my detailed debug log. I hope this helps to recognize why preventing resolution of the config file.

First, let me make clear this case is helpless for multiple configs in a workspace (Check out #218) and user's basic mistake (e.g. lacked `npm install`).

Now, tailwindcss-intellisense tries finding out configuration file faster as far as possible, powered by [fast-glob](https://github.com/mrmlnc/fast-glob) module. For efficient work of finding, it internally spawns concurrency threads as many as the number of CPUs. [`cpus()` in Node.js `os` module](https://nodejs.org/api/os.html#os_os_cpus) is commonly used to detect how many CPUs there are.

The problem is that getting CPU information is restricted in some environments by various reasons. In Linux, Node.js (libuv) tries to access `/proc/stat` for getting CPUs. However, some Linux distributions deny to access for secure, so may return an empty array or `undefined` instead of correct CPU infos (e.g. Android: https://github.com/nodejs/node/issues/19022). In this case, the current fast-glob tries to spawn 0 threads, which means never started glob processes for resolution of config files.

So an original report of this issue may be caused by not accessible `/proc/stat`, if assumed he is avoiding some pitfalls.

In addition, VS Code exploration for Mac ARM64 (Apple Silicon) is also returning an empty array for some reason: https://github.com/microsoft/vscode/issues/112122. Of course, the result is same in this case.

Fortunately fast-glob has patched to deal with this problem. It spawns  at minimum 1 process even if detected 0 CPUs (https://github.com/mrmlnc/fast-glob/pull/296). The extension is going to become work correctly by waiting for update of fast-glob and updating dependency.

**Comment by uncvrd** [comment] 2020-12-16 06:43
Also reporting in that intellisense works on my "business" Intel Macbook Pro but does not work on my "personal" Apple Silicon Macbook Pro

**Comment by thiras** [comment] 2020-12-16 23:42
> @thiras can I ask what specifically isn't working? Your screenshot indicates that it is working fine, since you have color decorators next to some of your classes (`bg-blue-500 text-white`), which are provided by the extension.

@bradlc I have been getting a lot of warnings and errors at CSS linting as the screenshot shows. And also I had zero logs under Tools > tailwindcss-intellisense. But somehow that output looks totally fine now despite the warning and errors at CSS linting

**Comment by yhatt** [comment] 2020-12-17 09:46
@thiras Please forgive my curious; could you share the result of following steps?

> 1. Toggle the Developer Tools
> 2. Type in console: `require('os').cpus()`
>
> _-- https://github.com/microsoft/vscode/issues/112122_

Developer Tools can open from `Help -> Toggle Developer Tools`.

If shown `[]` (empty array) by typing in that and hitting enter, we can make certain that the root issue will be resolved your trouble by https://github.com/tailwindlabs/tailwindcss-intellisense/pull/226.

**Comment by edwinhollen** [comment] 2020-12-18 15:08
> @thiras Please forgive my curious; could you share the result of following steps?
> 
> > 1. Toggle the Developer Tools
> > 2. Type in console: `require('os').cpus()`
> > 
> > _-- [microsoft/vscode#112122](https://github.com/microsoft/vscode/issues/112122)_
> 
> Developer Tools can open from `Help -> Toggle Developer Tools`.
> 
> If shown `[]` (empty array) by typing in that and hitting enter, we can make certain that the root issue will be resolved your trouble by #226.

Hi @yhatt 🙂 I can confirm this array is empty on my M1 Macbook Air, and I'm using VS Code Exploration build. 

![macos-os-cpus-empty-vs-code-exploration](https://user-images.githubusercontent.com/950704/102629182-cda38b80-4118-11eb-82a8-2b0f2d87c75e.jpg)

VS Code Exploration version info: 
```
Version: 1.53.0-exploration
Commit: fc70eeb302032bd8cafe8a87246b822034ea5b9d
Date: 2020-12-14T07:00:42.229Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0
```

**Comment by edwinhollen** [comment] 2020-12-18 15:29
p.s. As a temporary workaround I'm running the Intel version of VS Code on my M1; the extension is working normally, and `require('os').cpus()` returns an array with 8 objects:

<img width="556" alt="Screen Shot 2020-12-18 at 10 28 13 AM" src="https://user-images.githubusercontent.com/950704/102631507-d053b000-411b-11eb-8343-a845de0355ad.png">

Hope this helps!

**Comment by yhatt** [comment] 2020-12-19 02:56
@edwinhollen Thanks!

But I'm interesting to this trouble on Linux; the original report of this issue shows occurred in Linux, not Apple Silicon Mac.

**Comment by progrium** [comment] 2020-12-30 21:18
Can you just have a way to force it on? Some of us don't have a single trace of JS or use a CDN or whatever

**Comment by nubpro** [comment] 2021-01-08 08:01
> I've also met this in VS Code 1.53 exploration for Apple Silicon.
> 
> https://github.com/tailwindlabs/tailwindcss-intellisense/blob/84e3bf4b3a81c3fb659bd58e28b95c9252cc0ee1/packages/tailwindcss-intellisense/src/class-names/index.js#L35
> 
> And curiously I've found this `glob` is never resolved in ARM64 build. It's working well in VS Code for Intel Mac build running through Rosetta 2.
> 
> For some reason, just changing `glob` to `glob.sync` will work on ARM64 well. Would it be better to submit pull request?
> 
> ```
> Version: 1.53.0-exploration
> Commit: d530b3b27d0f52a0290cdb53031ba60f02927c60
> Date: 2020-12-10T07:00:45.477Z
> Electron: 11.0.3
> Chrome: 87.0.4280.67
> Node.js: 12.18.3
> V8: 8.7.220.25-electron.0
> OS: Darwin arm64 20.1.0
> ```
> 
> #### Related
> * [#209 (comment)](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/209#issuecomment-740316046)
> * [microsoft/vscode#106770 (comment)](https://github.com/microsoft/vscode/issues/106770#issuecomment-743311309)
> * [microsoft/vscode#112225](https://github.com/microsoft/vscode/issues/112225)
> 
> #### Note
> It will resolve a specific case for Apple Silicon, but [an original issue](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/209#issue-737551151) that is happening in Linux x64 may not resolve.

How can one manually update this `glob` to `glob.sync` manually? Does this require repackaging the extension?

Would love to hear from you soon.

**Comment by bradlc** [comment] 2021-01-08 16:42
Going to close this because it's gone totally off-topic 😅 Please open separate issues if you're having problems.

To address the original issue @thiras: Those errors come from the built-in VS Code CSS validation. You can disable this by setting the `css.validate` setting to `false` (there's also a `scss.validate` setting if you're using SCSS)

**Closed by bradlc** 2021-01-08 16:42 UTC

**Comment by filipac** [comment] 2021-01-08 17:38
@bradlc the issue i mentioned still remains: if multiple tailwind config files are in the same workspace, extension picks the first one which might not be installed and won;t work.

**Comment by Hahlh** [comment] 2021-02-11 11:01
I would like to add here, that for me to problem apparently was caused by the tailwind.config.js not being tracked by git. ([source](https://stackoverflow.com/a/66056300)).

**Comment by xChristianZx** [comment] 2021-02-12 17:43
@filipac Thank you for noting this. I can confirm as I'm currently in the middle of a refactor with two tailwind.config.js files in the workspace. 

Deleting the old one cleared up the `TypeError: Cannot read property 'classNames' of undefined at` as originally noted by @wadhah101. Intellisense is now working as expected.

**Comment by k1ngzed** [comment] 2021-05-17 06:55
I have a problem getting postcss
`Tailwind CSS: Can't resolve 'postcss' in 'd:\work\`

In my project path, there is a file name with **'#'** **'d:\work\\#files\project\`**
Recently, either vscode was updated or it is not clear what happened and this is the problem that has arisen! this has never happened before!

Removed the **'#'** from the file path, everything works.

**Comment by tsuifei** [comment] 2021-09-20 14:46
I've been trying to get it to work for a while, but it hasn't worked. I've searched for a lot of information, but I saw @sanny-io's suggestion: install HTML CSS Support, and it actually works!

This solution worked for me (I don't know why to 👀)
https://stackoverflow.com/a/63549595

The exact same behavior here when working with Vue files, the colors don't show.
Hopefully I can find out why the colors don't show up.

**Comment by zackha** [comment] 2023-02-15 12:03
If you are working with nuxt3, you can try this.

Add the following configuration to your `.vscode/settings.json file`, so that Tailwind directives have proper autocomplete, syntax highlighting, and linting:

```
"tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs"
"files.associations": {
    "*.css": "tailwindcss"
}
```

detailed: [link](https://tailwindcss.nuxt.dev/tailwind/editor-support)
