### ISSUE TITLE
`EACCES: permission denied` when starting

### ISSUE THREAD

**Issue by logikaljay** [tailwindlabs/tailwindcss-intellisense#174] opened 2020-08-22 21:17 UTC
The extension crashes on start when it doesn't have permission to a folder or file in the project.

Example:

```
Error: EACCES: permission denied, scandir '/home/jay/tailwindcss-intellisense-crash-example/data/mongo/journal'
Emitted 'error' event at:
    at c._handleError (/home/jay/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.4.2/dist/server/index.js:1:261315)
    at /home/jay/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.4.2/dist/server/index.js:1:261016
    at worked (/home/jay/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.4.2/dist/server/index.js:13:95816)
    at /home/jay/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.4.2/dist/server/index.js:1:261133
    at l (/home/jay/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.4.2/dist/server/index.js:1:190033)
    at /home/jay/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.4.2/dist/server/index.js:1:189246
    at fs.js:153:23
    at FSReqCallback.req.oncomplete (fs.js:778:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/home/jay/tailwindcss-intellisense-crash-example/data/mongo/journal'
}
```

**Comment by bradlc** [comment] 2020-08-25 15:16
Hey @logikaljay. What do you think is the expected behaviour in this situation?

**Comment by logikaljay** [comment] 2020-08-26 05:45
If the extension can't read the directory, I would expect it to just be skipped.

**Comment by kfriars** [comment] 2020-08-31 15:47
I also have this issue. My use case is that I use docker, and the containers store data in a "docker/.data" directory inside my project. It is a real pain to configure a docker container to write to shared volumes in a manner that is readable and writeable by the host user.

"Hey @logikaljay. What do you think is the expected behaviour in this situation?"

For me, I think the expected behavior is fine. However, I would like the ability to exclude directories from being scanned as a setting. Most extensions have this kind of setting. Even if it could look up the "files.exclude" setting, that would work for me.

**Comment by faisalhakim47** [comment] 2020-10-16 04:25
I also have this issue because using docker volume in my project. I suggest that tailwind can use the .gitignore for starting point to exclude unwanted files.

**Comment by bradlc** [comment] 2021-01-08 16:32
Going to close this as the original issue is resolved. With regards to excluding files let's track that over at #139 👍

**Closed by bradlc** 2021-01-08 16:32 UTC
