### ISSUE TITLE
Not working with multiple projects in a workspace

### ISSUE THREAD

**Issue by dspacejs** [tailwindlabs/tailwindcss-intellisense#379] opened 2021-08-03 06:20 UTC
I have a workspace with the multiple projects:

```
app1/
app2/
```

Both `app1` and `app2` have their own Tailwind configs and `tailwindcss` independently installed.

If I open one of these apps in VSCode, IntelliSense will pick up its config without issues.

But if I open the workspace (which contains both apps), it will load the first config it finds (which is `app1`). This means if I'm working on `app2`, IntelliSense will still be using the config from `app1` (so it doesn't work). 

I have a `myproject.code-workspace` file like this:

```json
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {
    "eslint.alwaysShowStatus": true,
    "eslint.workingDirectories": ["app", "component-library", "server"]
  }
}

```

It should just be working, but it's not.

**Comment by bradlc** [comment] 2021-08-12 15:54
Duplicate of #218

**Closed by bradlc** 2021-08-12 15:54 UTC
