### ISSUE TITLE
Feature request: Using the extension without an Javascript Environment (ASP.NET / Blazor)

### ISSUE THREAD

**Issue by jtheisen** [tailwindlabs/tailwindcss-intellisense#259] opened 2021-02-07 11:16 UTC
The extension works fine for me on Javascript-based projects, but for ASP.NET projects using razor files for the html templates there's usually no Javascript environment and no `package.json`. The build is done with `msbuild`, not `npm`.

But the extension needs all that, at least that's what I'm taking away from the documentation.

I understand that in order to use tailwind properly, the important compile and pruning steps require the Javascript world anyway.

However, if it would still be nice if the extension worked without it (at least with the default configuration of tailwind), as then I can just start hacking and worry about the rest later.

**Comment by bradlc** [comment] 2021-02-07 20:33
Going to close this as a duplicate of #27 as I think that covers the "no JS" use case 👍

**Closed by bradlc** 2021-02-07 20:33 UTC
