### ISSUE TITLE
Issue with experimental classRegex limit

### ISSUE THREAD

**Issue by AndysonDK** [tailwindlabs/tailwindcss-intellisense#514] opened 2022-04-01 19:20 UTC
I'm getting the following error:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/28491857/161325930-10cc4777-6dff-4538-8f42-8f9e231c58fd.png">

Hovering, linting and autocompletion doesn't work for me. Does it have something to do with the [limit](https://github.com/tailwindlabs/tailwindcss/issues/7553#issuecomment-922237989)? If so, can it be increased somehow?
The problem occurs in this repo: https://github.com/AndysonDK/syncbase/tree/59c7026584576f006925f6bcee60c80bd581dad9

_Originally posted by @AndysonDK in https://github.com/tailwindlabs/tailwindcss/discussions/7554#discussioncomment-2488163_

Okay I have now updated the regex, and it works somewhat as you can see here:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/28491857/161338543-0763909d-92ac-4008-8786-de3d606c6c4a.png">
This code is from this version of the repo: https://github.com/AndysonDK/syncbase/tree/3506c159331b65768385bc0826a3f2f8811367c5

The tailwindcss classes inside the closeButtonClasses function doesn't work at all, so it seems like there is some kind of regex limit

**Comment by bradlc** [comment] 2022-04-20 11:12
Hey @AndysonDK. I'm pretty sure this is a duplicate of #499 and the issue was fixed in #501. Update the extension to the latest version (currently `v0.8.1`) and you should be good to go 👍

**Closed by bradlc** 2022-04-20 11:12 UTC

**Comment by henrychea** [comment] 2022-07-19 18:08
How would I go about using regex to match all in between the ' in this `tw.style('text-sm', cool 'bg-blue-100', 'flex-row mb-2')`

Matching so it becomes this tw.style('**text-sm**', cool '**bg-blue-100**', '**flex-row mb-2**')
