### ISSUE TITLE
Loading issue with plugin - input.matchAll is not a function

### ISSUE THREAD

**Issue by Braunson** [tailwindlabs/tailwindcss-intellisense#606] opened 2022-09-15 14:45 UTC
**What version of Tailwind CSS IntelliSense are you using?**
v0.8.7

**What version of Tailwind CSS are you using?**
^2.1.2

**What package manager are you using?**
npm

**What operating system are you using?**
Windows

**Reproduction URL**
N/A Currently

**Describe your issue**

This error is appearing 

```
Tailwind CSS: input.matchAll is not a function or its return value is not iterable
```

Further output:
```
[Error - 10:35:28 AM] Tailwind CSS: input.matchAll is not a function or its return value is not iterable
TypeError: input.matchAll is not a function or its return value is not iterable
    at splitAtTopLevelOnly (c:\Users\Braunson\Documents\GitHub\project\node_modules\tailwindcss\lib\util\splitAtTopLevelOnly.js:59:29)
    at splitAtTopLevelOnly.next (<anonymous>)
    at Function.from (<anonymous>)
    at parseBoxShadowValue (c:\Users\Braunson\Documents\GitHub\project\node_modules\tailwindcss\lib\util\parseBoxShadowValue.js:27:25)
    at shadow (c:\Users\Braunson\Documents\GitHub\project\node_modules\tailwindcss\lib\corePlugins.js:3121:76)
    at wrapped (c:\Users\Braunson\Documents\GitHub\project\node_modules\tailwindcss\lib\lib\setupContextUtils.js:397:46)
    at resolveMatches (c:\Users\Braunson\Documents\GitHub\project\node_modules\tailwindcss\lib\lib\generateRules.js:545:47)
    at resolveMatches.next (<anonymous>)
    at Function.from (<anonymous>)
    at Object.generateRules [as module] (c:\Users\Braunson\Documents\GitHub\project\node_modules\tailwindcss\lib\lib\generateRules.js:678:29)
```

**Comment by Braunson** [comment] 2022-09-15 17:18
@bradlc 

```javascript
const { colors } = require('tailwindcss/defaultTheme');
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: {
        layers: ['utilities'],
        content: [
            './app/**/*.php',
            './resources/**/*.html',
            './resources/**/*.js',
            './resources/**/*.jsx',
            './resources/**/*.ts',
            './resources/**/*.tsx',
            './resources/**/*.php',
            './resources/**/*.vue',
            './resources/**/*.twig',
            './resources/css/**/*.css',
            './resources/views/**/*.blade.php',
            './vendor/livewire-ui/modal/resources/views/*.blade.php',
            './storage/framework/views/*.php',
        ],
        options: {
            defaultExtractor: (content) => content.match(/[\w-/.:]+(?<!:)/g) || [],
            safelist: [
                /-active$/, /-enter$/, /-leave-to$/, /show$/,
                'bg-red-50', 'bg-blue-50', 'bg-yellow-50', 'bg-green-50',
                'border-red-200', 'border-blue-200', 'border-yellow-200', 'border-green-200',
                'text-red-800', 'text-blue-800', 'text-yellow-800', 'text-green-800',
                'text-red-700', 'text-blue-700', 'text-yellow-700', 'text-green-700',
                'text-salmon-pink-500', 'bg-salmon-pink-500', 'bg-salmon-pink-100', 'hover:bg-salmon-pink-500',
                'text-deep-lavender-500', 'bg-deep-lavender-500', 'bg-deep-lavender-100', 'hover:bg-deep-lavender-500',
                'text-lightish-blue-500', 'bg-lightish-blue-500', 'bg-lightish-blue-100', 'hover:bg-lightish-blue-500',
                'bg-indigo-500', 'bg-indigo-300', 'hover:bg-indigo-500', 'text-indigo-800',
                'bg-red-500',
            ],
        },
    },
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                "dark": "#26313d",
                "pale-grey": "#f7f8fa",
                "danger-red": "#ff6e6e",
                current: "currentColor",
                transparent: "transparent",
                white: "#ffffff",
                black: "#000000",
                gray: {
                    50: "#f9fafb",
                    100: "#f4f5f7",
                    200: "#e5e7eb",
                    300: "#d2d6dc",
                    400: "#9fa6b2",
                    500: "#6b7280",
                    600: "#4b5563",
                    700: "#374151",
                    800: "#252f3f",
                    900: "#161e2e",
                },
                red: {
                    50: "#fdf2f2",
                    100: "#fde8e8",
                    200: "#fbd5d5",
                    300: "#f8b4b4",
                    400: "#f98080",
                    500: "#f05252",
                    600: "#e02424",
                    700: "#c81e1e",
                    800: "#9b1c1c",
                    900: "#771d1d",
                },
                orange: {
                    50: "#fff8f1",
                    100: "#feecdc",
                    200: "#fcd9bd",
                    300: "#fdba8c",
                    400: "#ff8a4c",
                    500: "#ff5a1f",
                    600: "#d03801",
                    700: "#b43403",
                    800: "#8a2c0d",
                    900: "#73230d",
                },
                yellow: {
                    50: "#fdfdea",
                    100: "#fdf6b2",
                    200: "#fce96a",
                    300: "#faca15",
                    400: "#e3a008",
                    500: "#c27803",
                    600: "#9f580a",
                    700: "#8e4b10",
                    800: "#723b13",
                    900: "#633112",
                },
                green: {
                    50: "#f3faf7",
                    100: "#def7ec",
                    200: "#bcf0da",
                    300: "#84e1bc",
                    400: "#31c48d",
                    500: "#0e9f6e",
                    600: "#057a55",
                    700: "#046c4e",
                    800: "#03543f",
                    900: "#014737",
                },
                blue: {
                    50: "#ebf5ff",
                    100: "#e1effe",
                    200: "#c3ddfd",
                    300: "#a4cafe",
                    400: "#76a9fa",
                    500: "#3f83f8",
                    600: "#1c64f2",
                    700: "#1a56db",
                    800: "#1e429f",
                    900: "#233876",
                },
                indigo: {
                    50: "#f0f5ff",
                    100: "#e5edff",
                    200: "#cddbfe",
                    300: "#b4c6fc",
                    400: "#8da2fb",
                    500: "#6875f5",
                    600: "#5850ec",
                    700: "#5145cd",
                    800: "#42389d",
                    900: "#362f78",
                },
                'yellow-orange': {
                    '50': '#fffaf5',
                    '100': '#fff6eb',
                    '200': '#fee8ce',
                    '300': '#fedab1',
                    '400': '#fdbf76',
                    '500': '#fca33b',
                    '600': '#e39335',
                    '700': '#bd7a2c',
                    '800': '#976223',
                    '900': '#7b501d'
                }
            },
            boxShadow: (theme) => ({
                ... theme('colors'),
                '3xl': '0 15px 50px -12px rgba(0, 0, 0, 0.25)',
                'outline-blue': `0 0 0 3px rgba(191, 219, 254, .5)`,
                xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
                outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
            }),
        },
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        gradientColorStops: (theme) => ({
            ... theme('colors'),
            'pale-gray': '#f7f8fa',
        }),
        pagination: (theme) => ({
            color: theme('colors.lightish-blue.500'),
            wrapper: 'flex justify-center list-reset',
            wrapper: {
                'display': 'flex',
                'justify-items': 'center'
            },
        }),
    },
    variants: {
        extend: {
            backgroundColor: ['group-focus', 'active'],
            borderColor: ['group-focus'],
            boxShadow: ['group-focus'],
            opacity: ['group-focus'],
            textColor: ['group-focus', 'active'],
            textDecoration: ['group-focus'],
        }
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
    ],
};
```

**Comment by bradlc** [comment] 2022-09-16 10:47
I cannot reproduce the issue with that config file and these versions:

```
@tailwindcss/aspect-ratio 0.4.2
@tailwindcss/forms 0.3.4
@tailwindcss/typography 0.4.1
tailwindcss: 2.1.2
```

Are you able to share your whole project?

**Comment by Braunson** [comment] 2022-09-17 04:34
@bradlc Unfortunately I cannot share the whole project. This however is the `package.json` versions..

```
"tailwindcss": "^2.1.2",
"@tailwindcss/aspect-ratio": "^0.2.1",
"@tailwindcss/forms": "^0.3.3",
"@tailwindcss/typography": "^0.4.1",
```

**Comment by mlabrum** [comment] 2022-10-19 00:05
I hit this when I attempted to use deeper levels within the boxShadow, but if I keep it flat then its fine e.g

```js
extend: {
			boxShadow: {
				black: { 
                                      Bottom: "inset 0px -1px 0px 0px rgba(0,0,0,0.8)",
				}
                       }
}
```

**Comment by bradlc** [comment] 2022-10-20 11:09
Ok I've managed to reproduce the error, and it's happening because although your project might be using Tailwind ^2.1.2, the extension is using ^3. This can happen if the extension is not able to resolve a version of Tailwind from within your project. The error refers to the `lib/util/splitAtTopLevelOnly.js` file but this does not exist in Tailwind 2.1.2.

Without a reproduction it's hard to tell why the extension cannot resolve your local copy of Tailwind, so I'm going to close this issue.

Side note: I would recommend removing `...theme('colors')` from your `boxShadow` config as this is the source of the error and doesn't really make sense. Check out the box shadow docs for details on expected config values: https://tailwindcss.com/docs/box-shadow#customizing-your-theme

**Closed by bradlc** 2022-10-20 11:09 UTC
