### ISSUE TITLE
Autocomplete does not work with @tailwind/typography 

### ISSUE THREAD

**Issue by szobX** [tailwindlabs/tailwindcss-intellisense#675] opened 2022-12-08 10:15 UTC
**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.9.1

**What version of Tailwind CSS are you using?**

For example: v3.2.4

**What package manager are you using?**

For example: yarn

**What operating system are you using?**

For example: linux

**Tailwind config**

```js
 plugins: [
        require('@tailwindcss/typography'),
        plugin(({ addVariant }) => {
            addVariant('svg', '&>svg')
            addVariant('svg-path', '&>svg>path')
        }),
        require('tailwindcss-labeled-groups')(['0', '1', '2']),
        require('@tailwindcss/line-clamp'),
    ],```

**VS Code settings**
```
```json
// Paste your VS Code settings in JSON format here
```

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

I have added @tailwind/typography to project. after rebuild project  tailwind returns me this error,     when l comment line responsible for require plugin, thats work

```
[Error - 11:08:29 AM] Tailwind CSS: Cannot read properties of null (reading '__isOptionsFunction')
TypeError: Cannot read properties of null (reading '__isOptionsFunction')
    at /home/szobi/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:9720
    at Array.map (<anonymous>)
    at /home/szobi/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:9705
    at _require.Ks.default.require (/home/szobi/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:178:45097)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/szobi/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:10084
    at Generator.next (<anonymous>)
    at /home/szobi/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:1:1219
    at new Promise (<anonymous>)
    at Xt (/home/szobi/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:1:1039)
    
    ```

**Comment by bradlc** [comment] 2022-12-08 15:41
Hey @szobX. Please provide a public GitHub repository that we can clone and open in VS Code to reproduce the issue. Unfortunately without that it will be impossible to track down the source of the issue.

My guess based on the error is that you're using Nuxt and this is a duplicate of https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663

**Comment by reinink** [comment] 2022-12-12 15:48
@szobX Hey since we haven't heard back I'm going to close this issue. However, if you're able to provide a reproduction as a public GitHub repo, we'd be happy to still take a closer look at it 👍

**Closed by reinink** 2022-12-12 15:48 UTC

**Comment by traez** [comment] 2025-08-05 03:24
This is a straightforward issue. 
Tailwind CSS Typography plugin is your sister plugin https://github.com/tailwindlabs/tailwindcss-typography
However VsCode intelisense doesn't work for its' styles same as for normal Tailwind CSS classes. So this causes difficulties when coding.

prose-headings:my-5
prose-heading:text-2xl
prose-p:mb-5
prose-p:leading-7
prose-li:list-disc
prose-li:leading-7
prose-li:ml-4
