### ISSUE TITLE
Unable to use it with Ember file structure

### ISSUE THREAD

**Issue by kurocygnus** [tailwindlabs/tailwindcss-intellisense#421] opened 2021-09-27 17:59 UTC
Hi.
I'm trying to use this in an Ember workspace, but the `tailwind.config.js` is on */config/
Because of this, it's not finding my prefix configuration. Any way to select the config location manually?

**Comment by bradlc** [comment] 2021-10-05 12:31
Hey @kurocygnus. Please can you share a GitHub repository that, when opened in VS Code, reproduces the issue?

**Comment by kurocygnus** [comment] 2021-10-05 15:00
Hey, sorry, I can't share the repository that this is happening, since it's not mine but from the company I work for.

**Comment by megalithic** [comment] 2021-11-17 21:08
i'm having a similar issue with Elixir Phoenix apps where these types of files reside in `repo_root/assets`; how might we tell tailwindcss-language-server to look there for tailwind.config.js and any related tailwind files (presets we might of created too).

**Comment by megalithic** [comment] 2021-12-03 15:33
@bradlc 

Here's the directory structure of an Elixir Phoenix application (notice where the highlighted tailwind config files are located):

![image](https://user-images.githubusercontent.com/3678/144629218-20a180a5-4b81-42dc-83b2-9e85b5806982.png)

**Comment by bradlc** [comment] 2022-02-04 11:08
I don't see any reason why the config wouldn't be picked up. Is there any output from the language server?

**Comment by oskarskog** [comment] 2022-02-05 20:33
I also have issues getting this working in a fresh Phoenix project and following the official instructions, [these](https://tailwindcss.com/docs/guides/phoenix), to install tailwind. I have been using it daily for Ember projects for about 4 months and it has worked like a charm, only seeing issues now that I'm trying to use it with Phoenix. 

I tried with neovim 6.0.1 and vscode.

The only thing showing up in the logs is this:
neovim:
```text
[START][2022-02-05 22:10:37] LSP logging initiated
[ERROR][2022-02-05 22:10:43] .../vim/lsp/rpc.lua:420	"rpc"	"tailwindcss-language-server"	"stderr"	"\n"
[ERROR][2022-02-05 22:10:43] .../vim/lsp/rpc.lua:420	"rpc"	"tailwindcss-language-server"	"stderr"	"warn - The RTL features in Tailwind CSS are currently in preview.\nwarn - Preview features are not covered by semver, and may be improved in breaking ways at any time.\n"
```

vscode:
```text
[2022-02-05 22:25:41.417] [exthost] [info] ExtensionService#_doActivateExtension bradlc.vscode-tailwindcss {"startup":false,"extensionId":{"value":"bradlc.vscode-tailwindcss","_lower":"bradlc.vscode-tailwindcss"},"activationEvent":"onStartupFinished"}
[2022-02-05 22:25:41.417] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/oskar/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/extension/index.js
```

Here is the test repo: [repo.zip](https://github.com/tailwindlabs/tailwindcss-intellisense/files/8008855/repo.zip)

**Comment by oskarskog** [comment] 2022-02-05 20:53
Thinking about it i realize that it probably doesn't work bc Phoenix doesn't install tailwind with node, it uses tailwind cli. Still, would be amazing if it was possible to have it working also in this case.

**Comment by bradlc** [comment] 2022-02-15 22:26
> Thinking about it i realize that it probably doesn't work bc Phoenix doesn't install tailwind with node, it uses standalone cli. Still, would be amazing if it was possible to have LSP working also in this case.

The extension works without a local version of `tailwindcss` since `v0.7.5`, so it should be fine. Your example project (`repo.zip`) works fine for me.

@kurocygnus Do you see anything in the `Output` panel? You can reveal this by running the `Tailwind CSS: Show Output` command from the command palette.

**Comment by bradlc** [comment] 2022-02-21 11:26
Ah I see. Sounds like this is a duplicate of #218 then 👍

**Closed by bradlc** 2022-02-21 11:26 UTC
