### ISSUE TITLE
Electron process uses the whole CPU

### ISSUE THREAD

**Issue by danieldietrich** [tailwindlabs/tailwindcss-intellisense#444] opened 2021-12-10 11:03 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.4

**What version of Tailwind CSS are you using?**

(unaffected / none)

**What package manager are you using?**

(unaffected / none)

**What operating system are you using?**

macOS Monterey 12.0.1

**Reproduction URL**

I can only provide you with the steps to reproduce because I see the effect on my local machine:

1. Install VS Code (currently 1.63.0)
2. Install the TailwindCSS IntelliSense Plugin (and ensure all other extensions are disabled, reload might be required)
3. Enable TailwindCSS IntelliSense extension
4. Open an new editor and save the blank file as test.sh
5. Wait a few seconds and observe the CPU sky-rocketing

https://user-images.githubusercontent.com/743833/145563670-ca2a3fe1-9504-4ca9-ac71-cd8bbfa1c78b.mp4

**Describe your issue**

When opening an existing file or saving a new file (even if empty), the CPU consumption of the Electron process immediately goes up > 100% and stays there, even if the file is closed.

**Comment by bradlc** [comment] 2021-12-13 18:27
Hey @danieldietrich. Please could you share the output of running `code --status | grep "tailwindServer"` on the command line, **while the CPU usage is spiking**?

**Comment by jylin** [comment] 2021-12-15 16:29
I've run into the same issue multiple times. Just now ran into it again and had to uninstall the plugin.

**Comment by danieldietrich** [comment] 2021-12-16 23:36
Today I got hight CPU load again. I switched from a MacBook Pro 2019 Intel to a MacBook Pro 2021 Apple Silicon. It was a fresh install of macOS with all apps, including VS Code + TailwindCSS Intelli Sense.

Educated guess: I versioned my user home dir with git (.gitignore whitelist + GIT_CEILING_DIRECTORIES=$HOME). There is a huge amount of sub-directories and files, some of them are not readable for non-privileged users (see all the scandir problems below). Does TW IntelliSense try to traverse all folders? May that be the reason for the high load?

@bradic please find the output of the command below (especially the last entry):

```sh
~⎇ main ❯ code --status | grep "tailwindServer"                         12:27AM
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/.Trash'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/.Trash'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Accounts'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Accounts'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/AddressBook'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/AddressBook'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/CallHistoryDB'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/CallHistoryDB'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/CallHistoryTransactions'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/CallHistoryTransactions'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/CloudDocs/session/db'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/CloudDocs/session/db'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/FileProvider'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/FileProvider'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/Knowledge'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/Knowledge'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/com.apple.TCC'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/com.apple.TCC'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Application Support/com.apple.sharedfilelist'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Application Support/com.apple.sharedfilelist'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Autosave Information'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Autosave Information'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Biome'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Biome'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Calendars'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Calendars'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Cookies'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Cookies'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/CoreFollowUp'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/CoreFollowUp'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/DuetExpertCenter'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/DuetExpertCenter'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/HomeKit'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/HomeKit'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/IdentityServices'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/IdentityServices'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Mail'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Mail'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Messages'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Messages'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/PersonalizationPortrait'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/PersonalizationPortrait'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Safari'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Safari'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Sharing'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Sharing'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Shortcuts'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Shortcuts'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/StatusKit'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/StatusKit'
}
[node.js fs] readdir with filetypes failed with error:  [Error: EPERM: operation not permitted, scandir '/Users/daniel/Library/Suggestions'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Users/daniel/Library/Suggestions'
}
  412	  2392	  2829	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/daniel/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.4/dist/server/tailwindServer.js --node-ipc --clientProcessId=774
```

**Comment by batjaa** [comment] 2022-01-26 16:16
Facing the same issue but with WebStorm. This boy is chugging the juice out of it:
```
$ ps aux | grep tailwind
batbob           19367 430.0  0.9  4745376 159032   ??  R     8:07AM  36:14.85 /Users/batbob/.nvm/versions/node/v12.18.0/bin/node /Users/batbob/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/212.5457.55/WebStorm.app/Contents/plugins/tailwindcss/server/tailwindServer.js
batbob           22738   0.0  0.0  4295976    772 s008  S+    8:15AM   0:00.01 grep tailwind
```

**Comment by multiplegeorges** [comment] 2022-03-26 21:41
VS Code: 1.65.2
Tailwind Intellisense: 0.7.7
Running in a Lucky Framework project.

tailwind.config.js:
```js
module.exports = {
  purge: [
    "./src/css/**/*.scss",
    "./src/pages/**/*.cr",
    "./src/components/**/*.cr"
  ],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
};
```

Output of `code --status | grep "tailwindServer"`:
```
  177	  2474	 89650	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/georges/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js --node-ipc --clientProcessId=89627
```

That's a lot of mem usage, wow.

**Comment by bradlc** [comment] 2022-09-02 12:33
Hey @danieldietrich. I'm curious if you're still experiencing this? Since your original post we have added exclusions so that when searching for a config file for example we won't look in `.git` folders. Since your home directory is versioned this may have improved things

**Comment by etalian** [comment] 2022-09-14 23:10
I am, just had to disable the extension as tailwindServer.js was chewing through my battery. Google led me here.
My hierarchy has symlinks to parent directories, which maybe sends the crawler in an infinite loop? Did not test without, but I can't image what else I could have out of the ordinary...
v0.8.7

**Comment by bjornharvold** [comment] 2022-11-25 02:35
Also experiencing the same issue. We have a 1300+ module monorepo and even with using exclude regex paths aggressively, the CPU goes bonkers for the entire day. Kicks in every time we try to auto-complete (intellisense) anything in the codebase.

**Comment by bradlc** [comment] 2023-03-20 11:23
Going to close this as it's not clear whether the original issue is still present following my previous comment on Sep 2, 2022. If anyone is still having problems please open a new issue **with full details of your project setup and a GitHub repository that we can clone to immediately reproduce the issue**. Thank you!

**Closed by bradlc** 2023-03-20 11:23 UTC
