### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by grmkris** [tailwindlabs/tailwindcss-intellisense#396] opened 2021-08-24 09:21 UTC
Hi can you push your extension to open-vsx.org in addition to VSCode Market Place so people using the FLOSS version could install it too?

Article on the subject: https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/

**Comment by bradlc** [comment] 2021-09-17 11:38
Duplicate of #219

**Closed by bradlc** 2021-09-17 11:38 UTC
