### ISSUE TITLE
Error occurred when exporting tailwind.config.js using esmodule

### ISSUE THREAD

**Issue by Zackin-He** [tailwindlabs/tailwindcss-intellisense#856] opened 2023-09-13 15:38 UTC
Tailwind CSS: Must use import to load ES Module: /Users/eternityx/Desktop/react/real-time-doc/tailwind.config.js require() of ES modules is not supported. require() of /Users/eternityx/Desktop/react/real-time-doc/tailwind.config.js from /Users/eternityx/.vscode/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename tailwind.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/eternityx/Desktop/react/real-time-doc/package.json.

**Comment by bradlc** [comment] 2023-09-14 08:59
Hey @Zackin-He. I'm going to close this because the issue template was not filled out. Please open a new issue providing the information requested in the template, including a GitHub repository that reproduces the issue. Thanks!

**Closed by bradlc** 2023-09-14 08:59 UTC
