### ISSUE TITLE
No intellisense for custom added utilities

### ISSUE THREAD

**Issue by demiro** [tailwindlabs/tailwindcss-intellisense#681] opened 2022-12-17 15:29 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./src/**/*.{html,vue}"],
  theme: {
    extend: {},
  },
  plugins: [],
};

```

**Describe your issue**

So, when I add custom utilities to my utilities layer like this:

```
@layer utilities {
  .elevation-1 {
    box-shadow: 0 0 2px 0 theme("colors.slate.600");
  }

  .elevation-2 {
    box-shadow: 0 0 4px 0 theme("colors.slate.600");
  }

  .elevation-3 {
    box-shadow: 0 0 6px 0 theme("colors.slate.600");
  }
}
```

and then trying to use it:

```
form {
    @apply flex items-center bg-white py-1 pl-4 pr-2 rounded-3xl;

    &:hover {
      @apply elevation-2;
    }
}
```

I get this

![image](https://user-images.githubusercontent.com/514682/208249281-d3ba76d0-7d1e-4dcb-bdde-ce40c50b2a4a.png)

**Comment by GreenDjango** [comment] 2022-12-27 02:34
I don’t think the extension offers intellisense for custom utilities from css files.

You can however add this in `tailwind.config.js` file:

```js
const defaultColors = require('tailwindcss/colors')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,vue}'],
  theme: {
    extend: {
      boxShadow: {
        'elevation-1': `0 0 2px 0 ${defaultColors.slate[600]}`, // shadow-elevation-1
        'elevation-2': `0 0 4px 0 ${defaultColors.slate[600]}`, // shadow-elevation-2
        'elevation-3': `0 0 6px 0 ${defaultColors.slate[600]}`, // shadow-elevation-3
      },
    },
  },
  plugins: [],
}
```

or use a custom plugin:

```js
const pluginCreator = require('tailwindcss/plugin')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,vue}'],
  theme: {
    extend: {},
  },
  plugins: [
    pluginCreator(function ({ addUtilities, theme }) {
      addUtilities({
        '.elevation-1': {
          boxShadow: `0 0 2px 0 ${theme('colors.slate.600')}`, // elevation-1
        },
        '.elevation-2': {
          boxShadow: `0 0 4px 0 ${theme('colors.slate.600')}`, // elevation-2
        },
        '.elevation-3': {
          boxShadow: `0 0 6px 0 ${theme('colors.slate.600')}`, // elevation-3
        },
      })
    }),
  ],
}
```

**Comment by bradlc** [comment] 2023-01-02 16:08
Going to close this as a duplicate of #227

**Closed by bradlc** 2023-01-02 16:08 UTC
