### ISSUE TITLE
Support for tailwindcss-rails

### ISSUE THREAD

**Issue by leehericks** [tailwindlabs/tailwindcss-intellisense#268] opened 2021-02-22 00:19 UTC
When installing gem [tailwindcss-rails](https://github.com/rails/tailwindcss-rails) without webpacker, default generated tailwindcss is available for use in a Rails project. There is no tailwind.config.js file. Is it possible to enable intellisense when this gem is found in the gemfile?

**Comment by bradlc** [comment] 2021-02-26 14:10
Duplicate of #247

**Closed by bradlc** 2021-02-26 14:10 UTC

**Comment by leehericks** [comment] 2021-02-26 14:19
Sorry I didn't see the duplicate. I don't know well about how these extensions work, but I do know that extensions are able to enable by checking the gemfile. I'm guessing though that without the tailwind.config.js you don't know what to intellisense?
