### ISSUE TITLE
Autocomplete doesn't work smoothly

### ISSUE THREAD

**Issue by dzdeveloper** [tailwindlabs/tailwindcss-intellisense#563] opened 2022-06-03 23:07 UTC
**What version of Tailwind CSS IntelliSense are you using?**

  v0.8.6

**What version of Tailwind CSS are you using?**

v3.0.24

**What package manager are you using?**
 npm

**What operating system are you using?**
Windows 10 

it's a bizarre issue ... when I open the quotation marks "" and type the first initials to a class name no suggestion shows up ... even after I type the whole class correctly ... the only way to get IntelliSense started is to add space inside " " before ordering a particular class ...

**Comment by mixja** [comment] 2022-07-09 01:34
I had this issue intermittently but at least for me I can reproduce it.

The issue seems to be if you autocomplete the containing class attribute, autocomplete for the first value in the class attribute doesn't work.  If you don't autocomplete the class attribute - i.e. type it all out - then autocomplete works inside the class attribute correctly.

In the example below, first of all I press tab to autocomplete the "class" attribute, and you can see autocomplete inside the attribute doesn't work.  Next I type out the "class" attribute myself, and autocomplete works:

https://www.loom.com/share/3dfa4c38b3ec46479c895f2a7d02d041

**Comment by bradlc** [comment] 2022-08-08 11:04
Thanks for the recording @mixja. Unfortunately this is just how VS Code works. There is no way for extensions to trigger completions in certain circumstances, such as following snippet insertion. In these cases you can trigger completions manually using VS Code's `Trigger Suggest` command (`Ctrl+Space`) – I hope that helps!

I'm going to close this because a recording has not been provided and I'm fairly sure it's going to be the same issue/solution described above. Please open a new issue if you think there's a bug somewhere, thanks!

**Closed by bradlc** 2022-08-08 11:04 UTC
