### ISSUE TITLE
IntelliSense doesn't seem to work in a multiple root workspace (when include root into workspace).

### ISSUE THREAD

**Issue by phuc-secomm** [tailwindlabs/tailwindcss-intellisense#462] opened 2022-01-11 03:18 UTC
Tailwind CSS IntelliSense v0.7.0
Tailwind CSS 3.0.7
Package manager: yarn
OS: macOS 12.1

**Steps to reproduce:**
**Case 1:** (NG)
```json
// mycode.code-workspace setting:
{
	"folders": [
		{
			"path": ".",
			"name": "root"
		},
		{
			"path": "./frontend-package" // my tailwind.config.js here
		},
		{
			"path": "./backend-package"
		}
	],
}
```
Result: Tailwind css IntelliSense service didn't start (don't exist in output and not working)
Expect: Tailwind css IntelliSense service start and working normally

**Case 2:** (OK)
```json
// mycode.code-workspace setting:
{
	"folders": [
		// removed root
		{
			"path": "./frontend-package" // my tailwind.config.js here
		},
		{
			"path": "./backend-package"
		}
	],
}
```
Result: Tailwind css IntelliSense service start and working normally

**Comment by bradlc** [comment] 2022-01-14 15:07
Hey @phuc-secomm. I can't reproduce this, are you able to share your project? Also, does the issue still occur if you update the extension to `0.7.5`?

**Comment by anhzf** [comment] 2022-02-08 16:38
Hello anyone still there? I'm facing this issue too. The workspace configuration is the same as mentioned the first above.

Currently, I create a symlink for my tailwind config to my root workspace.
But in the future, it will break if there are many projects that have multiple tailwind config (just worried, I think it's a small possibility 😀✌️).

**Comment by garlandcrow** [comment] 2022-02-23 01:25
I can't even get it to activate with the symbolic link hack anymore over the last week. There is no setup I can do with a monorepo that can get it to activate. I haven't found a way to debug this since I can't see any logs for an extension that doesn't activate.

**Comment by JamesYeoman** [comment] 2022-02-28 14:02
I'd like to add to this. I have a shared config for tailwind that sets up daisyui and defines some colours. I then have a config for my storybook package and a config for my frontend package. I opened up my root package.json and tailwindcss activated, and seemingly randomly picked the storybook config. I then opened App.tsx in the frontend package and there aren't any logs to suggest the extension loaded the frontend tailwind config.

This is the extension output.
![extension output](https://user-images.githubusercontent.com/21042602/155995843-afa82363-fdb3-446b-9125-69b060650c13.png)
That's all I got. Nothing new after opening App.tsx

For reference, [here's the repo](https://github.com/JamesYeoman/dsrbmm) that I'm talking about

**Comment by bradlc** [comment] 2022-04-20 14:42
I'm closing this because a reproduction has not been provided. Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but without a reproduction it's just not going to be possible to identify and debug the issue.

If anyone is able to share a repository that I can clone and immediately see the problem please open a new issue and I'd be happy to take a look 👍

**Closed by bradlc** 2022-04-20 14:42 UTC
