### ISSUE TITLE
Tailwind CSS IntelliSense will not working when vue template code have slot

### ISSUE THREAD

**Issue by linbaijin** [tailwindlabs/tailwindcss-intellisense#531] opened 2022-04-18 07:59 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.1

**What version of Tailwind CSS are you using?**

v3.0.23

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS 11.2.2

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

![image](https://user-images.githubusercontent.com/45031055/163776810-d208a351-7cfe-4550-950a-6f9b61d454da.png)

Tailwind CSS IntelliSense v0.7.7 don't have that problem

**Comment by aibmakesense** [comment] 2022-04-19 01:50
https://github.com/tailwindlabs//issues/528

**Comment by bradlc** [comment] 2022-04-19 10:12
Duplicate of #528

**Closed by bradlc** 2022-04-19 10:12 UTC
