### ISSUE TITLE
Tailwind Intellisense is adding `tw-` prefixes to all classes

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [tailwindlabs/tailwindcss-intellisense#704] opened 2023-01-25 21:51 UTC
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.6

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Tailwind config**

```js
module.exports = {
    prefix: '',
    content: [
        '../src/templates/**/*.{twig,html}',
        '../src/vue/**/*.{vue,js}',
    ],
    safelist: [ ],
    theme: {
        extend: {
            typography: (theme) => ({
                DEFAULT: {
                    css: {
                        '--tw-prose-bullets': theme('colors.neutral.800'),
                        'ul li, ol li, p, span': {
                            color: theme('colors.neutral.800'),
                            fontSize: theme('fontSize.sm'),
                            lineHeight: theme('leading.tight'),
                        },
                        'ul, ol': {
                            'margin-inline': theme('spacing.4'),
                        },
                        'ul ul, ol ul': {
                            'margin-block': theme('spacing.1'),
                        },
                        'ul li ul, ol li ul, ul ol li, ol ul li': {
                            'margin-block': '0',
                        },
                        'li': {
                            'margin-block': theme('spacing.1'),
                            'padding-left': '0',
                        },
                        'li p': {
                            'margin-block': '0',
                        },
                        'a': {
                            color: theme('colors.neutral.800'),
                            'text-decoration': 'none',
                        },
                        'a:hover, a:focus': {
                            'text-decoration': 'underline',
                        },
                        'h1, h2, h3, h4, h5, h6': {
                            color: theme('colors.neutral.800'),
                        },
                    },
                },
            }),
            colors: {
                black: '#212529',
                blue: {
                    600: '#007bff',
                },
                emerald: {
                    200: '#a0d0cb',
                },
                red: {
                    500: '#dc5940',
                },
                rose: {
                    700: '#c82333',
                },
                neutral: {
                    200: '#e4e4e4',
                    800: '#212529',
                },
                slate: {
                    200: '#e3f1f0',
                    500: '#426ca9',
                    600: '#345484',
                    700: '#2c3c56',
                },
                gray: {
                    50: '#f8f9fa',
                    100: '#f4f5f7',
                },
                zinc: {
                    200: '#dee2e6',
                    500: '#000000',
                },
            },
            fontSize: {
                '32px': ['2rem', {
                    lineHeight: '1.2',
                }],
                '40px': ['2.5rem', {
                    lineHeight: '1.2',
                }],
            },
            aspectRatio: {
                '1/2': '1 / 2',
                '2/1': '2 / 1',
            },
        },
        container: {
            screens: {
                sm: '600px',
                md: '720px',
                lg: '960px',
                xl: '1140px',
            },
        },
    },
    plugins: [
        require('@tailwindcss/aspect-ratio'),
        require('@tailwindcss/line-clamp'),
        require('@tailwindcss/typography'),
    ],
};

```

**VS Code settings**

```json
{
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "[javascript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "beautify.language": {
    "css": [
      "css",
      "less",
      "scss"
    ],
    "html": [
      "htm",
      "html"
    ],
    "js": {
      "filename": [
        ".jshintrc",
        ".jsbeautifyrc"
      ],
      "type": [
        "javascript",
        "json",
        "jsonc"
      ]
    }
  },
  "cSpell.userWords": [
    "lazysizes",
    "pcss",
    "performant"
  ],
  "diffEditor.ignoreTrimWhitespace": false,
  "editor.accessibilitySupport": "off",
  "editor.guides.bracketPairs": true,
  "emmet.includeLanguages": {
    "twig": "twig"
  },
  "emmet.showSuggestionsAsSnippets": true,
  "emmet.triggerExpansionOnTab": true,
  "files.associations": {
    "*.pcss": "vue-postcss"
  },
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "git.ignoreRebaseWarning": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "prettier.enableDebugLogs": true,
  "prettier.jsxBracketSameLine": true,
  "prettier.requirePragma": true,
  "prettier.tabWidth": 4,
  "prettier.useTabs": true,
  "security.workspace.trust.untrustedFiles": "newWindow",
  "tailwindCSS.emmetCompletions": true,
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1"
  },
  "workbench.editor.untitled.hint": "hidden",
  "workbench.startupEditor": "newUntitledFile",
  "[css]": {
    "editor.defaultFormatter": "stylelint.vscode-stylelint"
  },
  "window.zoomLevel": 3,
  "terminal.external.osxExec": "Warp.app",
  "tailwindCSS.includeLanguages": {
    "twig": "html"
  }
}
```

**Reproduction URL**

_Not sure how to provide this_

**Describe your issue**

For whatever reason TW Intellisense is adding a `tw-` prefix to all of my autocomplete class attachments:

![Screenshot 2023-01-18 at 1 10 31 PM](https://user-images.githubusercontent.com/39201467/214699096-77d49a6b-f0c2-4444-b56c-40d7921f345c.png)

I don't recall when this all started but I'd like to determine what's causing it. I love this handy plugin and thank you, and your team, for making our lives easier :)

**Comment by michtio** [comment] 2023-01-26 08:15
I am encountering the same issue. While nothing in the Tailwind Config file is configured to even use a prefix, the intellisense does pick up on the config and read the custom changes and values in there. Yet for autocomplete everything gets prefixed with `tw-`

**Comment by wakoodi** [comment] 2023-01-26 08:18
I am encountering the same issue. Same as above, nothing in the TW config is configured to use a prefix.

**Comment by bradlc** [comment] 2023-01-26 10:20
Hey @DynamiteGoesBoom. Please can you provide a GitHub repository that I can clone and open in VS Code to reproduce the issue?

**Comment by michtio** [comment] 2023-01-27 08:42
Hey @bradlc , I looked a little further into this. It will not a coincidence, but the above people are all working with the same folder structure. In a docker environment it is built as follows:

```
.
├── CHANGELOG.md
├── LICENSE.md
├── Makefile
├── README.md
├── buddy.yml
├── buildchain
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── postcss.config.js
│   ├── src -> ../src
│   ├── tailwind.config.js
│   ├── tsconfig.json
│   └── vite.config.ts
├── cms
│   ├── bootstrap.php
│   ├── composer.json
│   ├── composer.lock
│   ├── config
│   ├── craft
│   ├── migrations
│   ├── modules
│   ├── storage
│   ├── templates
│   ├── vendor
│   └── web
├── db-seed
│   └── db-seed.sql
├── docker-compose.yml
├── docker-config
│   ├── mysql
│   ├── nginx
│   ├── node-dev-vite
│   ├── php-dev-craft
│   ├── php-prod-craft
│   └── redis
├── scripts
│   ├── common
│   ├── docker_pull_db.sh
│   └── docker_restore_db.sh
├── src
│   ├── conf
│   ├── css
│   ├── fonts
│   ├── img
│   ├── js
│   ├── templates -> ../cms/templates
│   ├── vue
│   └── web
```

As you can see the tailwind config file is in the "buildchain" subfolder. If I take a copy and drop in the root of the project as follows:

```
.
├── CHANGELOG.md
├── LICENSE.md
├── Makefile
├── README.md
├── buddy.yml
├── buildchain
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── postcss.config.js
│   ├── src -> ../src
│   ├── tailwind.config.js
│   ├── tsconfig.json
│   └── vite.config.ts
├── cms
│   ├── bootstrap.php
│   ├── composer.json
│   ├── composer.lock
│   ├── config
│   ├── craft
│   ├── migrations
│   ├── modules
│   ├── storage
│   ├── templates
│   ├── vendor
│   └── web
├── db-seed
│   └── db-seed.sql
├── docker-compose.yml
├── docker-config
│   ├── mysql
│   ├── nginx
│   ├── node-dev-vite
│   ├── php-dev-craft
│   ├── php-prod-craft
│   └── redis
├── scripts
│   ├── common
│   ├── docker_pull_db.sh
│   └── docker_restore_db.sh
├── src
│   ├── conf
│   ├── css
│   ├── fonts
│   ├── img
│   ├── js
│   ├── templates -> ../cms/templates
│   ├── vue
│   └── web
└── tailwind.config.js
```

Then the VS Code Intellisense works without an issue and it won't prefix the autosuggestions.
Now this hasn't been an issue in the past, since for years projects are structured like this, but honestly not an idea as to when this issue started arising.

It should be so that at least VSCode can detect the tailwind config fully in subfolders. I can always create a minimal reproduction somewhere next week if needed. But honestly I think it's very clear that it's just not picking up the tailwind config nicely when it's living in a subdir.

**Comment by bradlc** [comment] 2023-01-27 09:46
We did update how config resolution works recently, which is why this may have changed. Without a reproduction I can't be 100% sure, but it seems like you have multiple Tailwind config files in your project (including some that you may not be aware of). You can see which config files the extension is picking up in the output panel (run the `Tailwind CSS: Show Output` command to reveal this).

In a complicated project structure like this with multiple Tailwind config files you may need to give the extension a hint as to which config file you want to use. You can use the `tailwindCSS.expermiental.configFile` setting to do this:

```
"tailwindCSS.experimental.configFile": "./buildchain/tailwind.config.js"
```

**Comment by michtio** [comment] 2023-01-28 11:57
@bradlc you are right in your answer. There are other "tailwind config files" in play that we aren't aware off. But I think they shouldn't be taken into consideration either.

```
[Global] Creating projects: {"folder":"/Users/michtio/dev/hdac","configPath":"/Users/michtio/dev/hdac/buildchain/tailwind.config.js","isUserConfigured":false,"documentSelector":[{"pattern":"/Users/michtio/dev/hdac/buildchain/tailwind.config.js","priority":0}{"folder":"/Users/michtio/dev/hdac","configPath":"/Users/michtio/dev/hdac/cms/vendor/craftcms/cms/src/web/assets/pluginstore/tailwind.config.js","isUserConfigured":false,"documentSelector":[{"pattern":"/Users/michtio/dev/hdac/cms/vendor/craftcms/cms/src/web/assets/pluginstore/tailwind.config.js","priority":0},{"folder":"/Users/michtio/dev/hdac","configPath":"/Users/michtio/dev/hdac/cms/vendor/craftcms/cms/src/web/assets/tailwindreset/tailwind.config.js","isUserConfigured":false,"documentSelector":[{"pattern":"/Users/michtio/dev/hdac/cms/vendor/craftcms/cms/src/web/assets/tailwindreset/tailwind.config.js","priority":0},
[Global] Adding watch patterns: /Users/michtio/dev/hdac/cms/vendor/craftcms/cms/src/web/assets/pluginstore/tailwind.config.js, 
[Global] Adding watch patterns: /Users/michtio/dev/hdac/cms/vendor/craftcms/cms/src/web/assets/tailwindreset/tailwind.config.js,
```

As you can see in the above ( run through the show output command ) there are some config files found in `vendor`.
In my honest opinion I do think that those shouldn't be found/taken into consideration at all.

--> If you install composer packages they'll end up in a `vendor` folder
--> if you install node packages they get installed in a `node_modules` folder

The TW intellisense package should never search in those folders unless explicitly told so, and not the other way around. It's safe to ignore vendor/node_modules. If people really need to read those configs, that should be configured. Same as when working on a project you wouldn't add those folders to your repo but `.gitignore` them.

**Comment by michtio** [comment] 2023-01-28 12:19
@bradlc as an extra I added in `**/vendor/**/*` to the watcherExclude setting within VSCode, so nothing should watch in those folders. Yet the Intellisense plugin keeps on looking in there, which might be that it's a non-recursive over recursive watcher? While a recursive watcher is definitely preferred.

![Screenshot 2023-01-28 at 13 17 43](https://user-images.githubusercontent.com/5818021/215266014-97136199-74ea-4d7a-8029-1b3372f1ffb5.png)

**Comment by DynamiteGoesBoom** [comment] 2023-01-30 18:02
Thanks to both of you rockstars @bradlc && @michtio 💪 The addition of `"tailwindCSS.experimental.configFile": "./buildchain/tailwind.config.js",` fixed the issue that I was having.

Thanks again

**Comment by bradlc** [comment] 2023-01-31 16:55
No problem! I'm going to close this because I consider the original issue to be resolved.

---

For reference, as well as the experimental `configFile` setting, the extension also has `tailwindCSS.files.exclude` setting, which can be used to exclude files or directories. For example if you want to exclude any `vendor` directories:

```diff
  "tailwindCSS.files.exclude": [
    "**/.git/**",
    "**/node_modules/**",
    "**/.hg/**",
    "**/.svn/**",
+   "**/vendor/**"
  ]
```

I think it's reasonable to expect this is be included by default so I'll definitely consider adding it 👍

**Closed by bradlc** 2023-01-31 16:55 UTC

**Comment by urbantrout** [comment] 2024-08-01 20:10
How can I set `tailwindCSS.files.exclude` when running `tailwindcss-language-server` from the command line? I use it with helix-editor and get the `tw-` prefixes because of a `vendor` folder.
