### ISSUE TITLE
Classes duplicate in auto-complete as you save when using Tailwind JIT

### ISSUE THREAD

**Issue by negcx** [tailwindlabs/tailwindcss-intellisense#316] opened 2021-05-09 15:52 UTC
I expect this is related to using JIT. It seems each time you save, JIT generates a new stylesheet perhaps, and it is then pulled into the VS Code extension. After developing for an hour or so, VS Code starts grinding to a halt when you want to type a class name as it seems to have a massive list.

![image](https://user-images.githubusercontent.com/5092613/117578599-47c6b380-b0ac-11eb-95d7-1d69ef68702e.png)

**Comment by bradlc** [comment] 2021-05-09 16:06
Hey @negcx. Are you able to share a project repository that reproduces this? Also, which operating system, VS Code version, extension version, and package manager are you using? Thanks!

**Comment by fredericseiler** [comment] 2021-05-10 14:53
Hi,

I can confirm this bug with JIT + [file watcher](https://laravel-mix.com/docs/6.0/cli#watch-assets-for-changes).

- macOS Big Sur 11.3.1
- VS Code 1.56.0
- Tailwind CSS IntelliSense 0.6.3
- npm 7.11.1
- TailwindCSS 2.1.1

`tailwind.config.js`
```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    mode: 'jit',

    purge: [
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography')
    ],
};
```

![image](https://user-images.githubusercontent.com/954168/117676930-48e00980-b1ae-11eb-9111-45ea34acf9af.png)

**Comment by fredericseiler** [comment] 2021-05-10 16:00
So, I just restarted VSCode, and the bug seems to have vanished, even after several css rebuilds under watcher... 🤷‍♂️

**Comment by bradlc** [comment] 2021-05-17 11:56
I have just pushed out a _potential_ fix for this in `v0.6.4` 🤞 I have not been able to reproduce the issue at all yet though. Please update the extension and let me know if the problem persists. If anybody is still seeing this a repository which reproduces the issue would be much appreciated, thanks!

**Comment by fredericseiler** [comment] 2021-05-17 12:15
I tried everything to reproduce it, in vain. I suspect it happened while I was toggling JIT mode on/off with Laravel Mix file-watcher running, but then again, can't confirm it.

**Comment by sergio101** [comment] 2021-05-17 14:19
hi, @bradlc .. I just installed  v0.6.4 and everything seems to be working fine now. Thanks!

**Comment by bradlc** [comment] 2021-05-28 17:13
Anyone still seeing this since `v0.6.4`? 👀

**Comment by bradlc** [comment] 2021-08-13 12:53
I'm going to assume this is resolved then 🤞 If not please open a new issue, thanks!

**Closed by bradlc** 2021-08-13 12:53 UTC
