### ISSUE TITLE
Extended theme properties not recognized

### ISSUE THREAD

**Issue by kriswuollett** [tailwindlabs/tailwindcss-intellisense#611] opened 2022-09-21 15:32 UTC
Tailwind CSS IntelliSense: `v0.8.7`
Tailwind CSS `3.1.8`
Package manager: `yarn`
OS: `macOS`

**Issue**

Having defined custom font-weight names:

<img width="398" alt="CleanShot 2022-09-21 at 10 30 14@2x" src="https://user-images.githubusercontent.com/1834192/191546884-92fa036b-46d7-463f-bd0a-1193ca2458b6.png">

They aren't recognized by IntelliSense:

<img width="1155" alt="CleanShot 2022-09-21 at 10 28 39@2x" src="https://user-images.githubusercontent.com/1834192/191546723-a4975a74-282a-4f19-9c0d-b74c0f870a0c.png">

But seems working fine as seen in Chrome dev tools:

<img width="556" alt="CleanShot 2022-09-21 at 10 31 20@2x" src="https://user-images.githubusercontent.com/1834192/191547178-44c7823f-6c75-4efa-9871-8f40e7548039.png">

Reloading vscode window doesn't help like it sometimes does for other issues.

**Comment by bradlc** [comment] 2022-09-21 17:10
Hey @kriswuollett. I can't reproduce this, are you able to share your project? Some things to check:

- Do you have multiple config files in your project? The extension may be using a different one to what you're expecting
- What can you see in the output panel (`Tailwind CSS: Show Output` command)?

**Comment by kriswuollett** [comment] 2022-09-21 18:44
Interesting I did not change anything since restarting the window and seeing the error highlighted, but now it is now recognized. Not sure at what point it fixed itself. The code is in a turborepo monorepo using yarn in a subdirectory of the git checkout:

```
Failed to load workspace modules.
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9

warn - The RTL features in Tailwind CSS are currently in preview.
warn - Preview features are not covered by semver, and may be improved in breaking ways at any time.
Found Tailwind CSS config file: /Users/kris/workspace/github.com/[COMPANY]/[PROJECT]/js/apps/[APP]/tailwind.config.js
Loaded postcss v8.4.16: /Users/kris/workspace/github.com/[COMPANY]/[PROJECT]/js/node_modules/postcss
Loaded tailwindcss v3.1.8: /Users/kris/workspace/github.com/[COMPANY]/[PROJECT]/js/node_modules/tailwindcss

warn - The RTL features in Tailwind CSS are currently in preview.
warn - Preview features are not covered by semver, and may be improved in breaking ways at any time.
```

**Comment by bradlc** [comment] 2022-09-22 09:12
Good to hear! I'm going to close this then, but please open a new issue if you run into this again and can provide a reproduction 👍

**Closed by bradlc** 2022-09-22 09:12 UTC
